
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Micronet
 */
public class Book extends javax.swing.JFrame {

    /**
     * Creates new form Book
     */
    public Book() {
        initComponents();
        menubook.setEnabled(false);    
        lblbalance.setVisible(false);
        tfbalance.setVisible(false);
        panelprice.setVisible(false);
        tfsearch.setVisible(false);
        combobooktype.setVisible(false);
        panelsearch.setVisible(false);
        panelaboutbook.setVisible(false);
        IFbookinventory.setVisible(false);
        btnbuybook.setEnabled(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/Images/orchid_books_shop.jpg")).getImage());
        tfusername.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panellogin = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        pfpassword = new javax.swing.JPasswordField();
        lblpassword = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        lblbalance = new javax.swing.JLabel();
        tfbalance = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        panelsearch = new javax.swing.JScrollPane();
        IFsearch = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combosearchcriteria = new javax.swing.JComboBox();
        tfsearch = new javax.swing.JTextField();
        combobooktype = new javax.swing.JComboBox();
        btnsearch = new javax.swing.JButton();
        panelprice = new javax.swing.JPanel();
        tfminprice = new javax.swing.JTextField();
        tfmaxprice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsearch = new javax.swing.JTable();
        btnclear = new javax.swing.JButton();
        lbliconbookshop = new javax.swing.JLabel();
        panelaboutbook = new javax.swing.JScrollPane();
        IFaboutbook = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        tfbookid = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        tfbooktitle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfauthor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfbooktype = new javax.swing.JTextField();
        btnbookdetails = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tfprice = new javax.swing.JTextField();
        lblbookimage = new javax.swing.JLabel();
        btnbuybook = new javax.swing.JButton();
        IFbookinventory = new javax.swing.JInternalFrame();
        jToolBar1 = new javax.swing.JToolBar();
        benexitinventory = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelsellbook = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfselloriginalprice = new javax.swing.JTextField();
        tfsellbookid = new javax.swing.JTextField();
        tfsellprice = new javax.swing.JTextField();
        tfsellbalance = new javax.swing.JTextField();
        btnsellbook = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        tfsellbooktitle = new javax.swing.JTextField();
        btndontsellbook = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbook = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        menubar = new javax.swing.JMenuBar();
        menugoback = new javax.swing.JMenu();
        menuexitbookshop = new javax.swing.JMenuItem();
        menubook = new javax.swing.JMenu();
        menusearchbook = new javax.swing.JMenuItem();
        menuaboutbook = new javax.swing.JMenuItem();
        menuoldbook = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ravie", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("Book Shop");

        panellogin.setBackground(new java.awt.Color(204, 204, 204));
        panellogin.setForeground(new java.awt.Color(0, 153, 204));

        lblusername.setText("Username");

        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });

        lblpassword.setText("Password");

        jLabel9.setText("Enter Username and Password To Continue");

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelloginLayout = new javax.swing.GroupLayout(panellogin);
        panellogin.setLayout(panelloginLayout);
        panelloginLayout.setHorizontalGroup(
            panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelloginLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelloginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblusername)
                    .addComponent(lblpassword))
                .addGap(22, 22, 22)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelloginLayout.createSequentialGroup()
                        .addComponent(tfusername)
                        .addGap(22, 22, 22))
                    .addGroup(panelloginLayout.createSequentialGroup()
                        .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelloginLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnsubmit)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelloginLayout.setVerticalGroup(
            panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelloginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusername)
                    .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassword)
                    .addComponent(pfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsubmit)
                .addGap(5, 5, 5))
        );

        lblbalance.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblbalance.setText("Balance");

        tfbalance.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N

        IFsearch.setVisible(true);

        jLabel2.setFont(new java.awt.Font("Vijaya", 1, 18)); // NOI18N
        jLabel2.setText("Search Book");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setText("Search Criteria");

        combosearchcriteria.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        combosearchcriteria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Search by Book Title", "Search by Author Name", "Search by Book Type", "Search by Book Price" }));
        combosearchcriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosearchcriteriaActionPerformed(evt);
            }
        });

        tfsearch.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N

        combobooktype.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        combobooktype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biography", "Chemistry", "Comics", "Computer", "Love", "Novel", "Physics", "Religious", "Series" }));

        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel5.setText("Maximum Price");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel4.setText("Minimum Price");

        javax.swing.GroupLayout panelpriceLayout = new javax.swing.GroupLayout(panelprice);
        panelprice.setLayout(panelpriceLayout);
        panelpriceLayout.setHorizontalGroup(
            panelpriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpriceLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(37, 37, 37))
            .addGroup(panelpriceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfminprice, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(tfmaxprice, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelpriceLayout.setVerticalGroup(
            panelpriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpriceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelpriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfminprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfmaxprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblsearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"BOOK_ID", "BOOK_TITLE", "AUTHOR", "BOOK_TYPE", "PRICE"},
                {null, null, null, null, null}
            },
            new String [] {
                "Book_ID", "Book_Title", "Author", "Book_Type", "Price"
            }
        ));
        tblsearch.setDragEnabled(true);

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IFsearchLayout = new javax.swing.GroupLayout(IFsearch.getContentPane());
        IFsearch.getContentPane().setLayout(IFsearchLayout);
        IFsearchLayout.setHorizontalGroup(
            IFsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFsearchLayout.createSequentialGroup()
                .addGroup(IFsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFsearchLayout.createSequentialGroup()
                        .addGroup(IFsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IFsearchLayout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IFsearchLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(combobooktype, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))
                        .addComponent(panelprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFsearchLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFsearchLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combosearchcriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnsearch)
                        .addGap(48, 48, 48)
                        .addComponent(btnclear))
                    .addGroup(IFsearchLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFsearchLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tblsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        IFsearchLayout.setVerticalGroup(
            IFsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFsearchLayout.createSequentialGroup()
                .addGroup(IFsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(IFsearchLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19)
                        .addGroup(IFsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnclear, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnsearch)))
                    .addGroup(IFsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combosearchcriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGroup(IFsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFsearchLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobooktype, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFsearchLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(IFsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tblsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        panelsearch.setViewportView(IFsearch);

        IFaboutbook.setVisible(true);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel6.setText("Enter Book_ID");

        tfbookid.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setText("Book Title");

        tfbooktitle.setEditable(false);
        tfbooktitle.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        tfbooktitle.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel8.setText("Author");

        tfauthor.setEditable(false);
        tfauthor.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel10.setText("Book Type");

        tfbooktype.setEditable(false);
        tfbooktype.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        btnbookdetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbookdetails.setText("View Details");
        btnbookdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookdetailsActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel11.setText("Price");

        tfprice.setEditable(false);
        tfprice.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        lblbookimage.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N

        btnbuybook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnbuybook.setText("BUY BOOK");
        btnbuybook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuybookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IFaboutbookLayout = new javax.swing.GroupLayout(IFaboutbook.getContentPane());
        IFaboutbook.getContentPane().setLayout(IFaboutbookLayout);
        IFaboutbookLayout.setHorizontalGroup(
            IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFaboutbookLayout.createSequentialGroup()
                .addGroup(IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFaboutbookLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfbookid, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnbookdetails))
                    .addGroup(IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(IFaboutbookLayout.createSequentialGroup()
                            .addGroup(IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(IFaboutbookLayout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addGroup(IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IFaboutbookLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfbooktitle, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(IFaboutbookLayout.createSequentialGroup()
                                    .addGroup(IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(IFaboutbookLayout.createSequentialGroup()
                                            .addGap(79, 79, 79)
                                            .addComponent(btnbuybook)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IFaboutbookLayout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addGroup(IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfbooktype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfauthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblbookimage, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IFaboutbookLayout.setVerticalGroup(
            IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFaboutbookLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfbookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbookdetails))
                .addGap(17, 17, 17)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfbooktitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFaboutbookLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfbooktype, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(29, 29, 29)
                        .addGroup(IFaboutbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(tfprice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(btnbuybook))
                    .addComponent(lblbookimage, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(903, Short.MAX_VALUE))
        );

        panelaboutbook.setViewportView(IFaboutbook);

        IFbookinventory.setVisible(true);

        jToolBar1.setRollover(true);

        benexitinventory.setText("Exit Inventory");
        benexitinventory.setFocusable(false);
        benexitinventory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        benexitinventory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        benexitinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benexitinventoryActionPerformed(evt);
            }
        });
        jToolBar1.add(benexitinventory);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel12.setText("Enter Book_ID");

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel14.setText("Original Price");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Sell Price");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Balance after Selling Book");

        tfselloriginalprice.setEditable(false);
        tfselloriginalprice.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        tfsellbookid.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        tfsellbookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsellbookidActionPerformed(evt);
            }
        });

        tfsellprice.setEditable(false);
        tfsellprice.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        tfsellbalance.setEditable(false);
        tfsellbalance.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        btnsellbook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsellbook.setText("Sell Book");
        btnsellbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsellbookActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel17.setText("Book Title");

        tfsellbooktitle.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        btndontsellbook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndontsellbook.setText("I Don't want to Sell the Book");
        btndontsellbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndontsellbookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelsellbookLayout = new javax.swing.GroupLayout(panelsellbook);
        panelsellbook.setLayout(panelsellbookLayout);
        panelsellbookLayout.setHorizontalGroup(
            panelsellbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(panelsellbookLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(tfsellbookid, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(panelsellbookLayout.createSequentialGroup()
                .addGroup(panelsellbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelsellbookLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsellbookLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelsellbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelsellbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfsellbalance, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfsellprice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfselloriginalprice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfsellbooktitle, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(panelsellbookLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnsellbook)
                .addGap(73, 73, 73)
                .addComponent(btndontsellbook)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelsellbookLayout.setVerticalGroup(
            panelsellbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsellbookLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelsellbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfsellbookid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelsellbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfsellbooktitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelsellbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfselloriginalprice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(29, 29, 29)
                .addGroup(panelsellbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfsellprice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(27, 27, 27)
                .addGroup(panelsellbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfsellbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(26, 26, 26)
                .addGroup(panelsellbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsellbook)
                    .addComponent(btndontsellbook))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Sell Books at Half Price", panelsellbook);

        tblbook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOOK_ID", "BOOK_TITLE", "BOOK_PRICE"
            }
        ));
        jScrollPane2.setViewportView(tblbook);

        jTabbedPane1.addTab("Show Books I Have", jScrollPane2);

        javax.swing.GroupLayout IFbookinventoryLayout = new javax.swing.GroupLayout(IFbookinventory.getContentPane());
        IFbookinventory.getContentPane().setLayout(IFbookinventoryLayout);
        IFbookinventoryLayout.setHorizontalGroup(
            IFbookinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(IFbookinventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        IFbookinventoryLayout.setVerticalGroup(
            IFbookinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFbookinventoryLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        menugoback.setText("Go Back");
        menugoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menugobackActionPerformed(evt);
            }
        });

        menuexitbookshop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuexitbookshop.setText("Exit BookShop");
        menuexitbookshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuexitbookshopActionPerformed(evt);
            }
        });
        menugoback.add(menuexitbookshop);

        menubar.add(menugoback);

        menubook.setText("Book");

        menusearchbook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menusearchbook.setText("Search Book");
        menusearchbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusearchbookActionPerformed(evt);
            }
        });
        menubook.add(menusearchbook);

        menuaboutbook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuaboutbook.setText("About Book");
        menuaboutbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuaboutbookActionPerformed(evt);
            }
        });
        menubook.add(menuaboutbook);

        menuoldbook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuoldbook.setText("Books I Have");
        menuoldbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuoldbookActionPerformed(evt);
            }
        });
        menubook.add(menuoldbook);

        menubar.add(menubook);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelaboutbook, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(IFbookinventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lblbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(tfbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(lbliconbookshop, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)))
                        .addComponent(panellogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblbalance)
                                    .addComponent(tfbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbliconbookshop, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panellogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IFbookinventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panelsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelaboutbook, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        try
        {
            String username=tfusername.getText();
            String password=pfpassword.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            String query = "SELECT * FROM Customer  WHERE username = '" +(username) + "' && password='"+(password)+"'" ;
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
                
                Double balance = rs.getDouble("balance");
                lblbalance.setVisible(true);
                tfbalance.setVisible(true);
                tfbalance.setEditable(false);
                tfbalance.setText(""+balance);
                panellogin.setVisible(false);
               

            }
            else
            {
                JOptionPane.showMessageDialog(this,"Invalid Username or Password");
                tfusername.setText("");
                pfpassword.setText("");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
         menubook.setEnabled(true);
         
        panellogin.setVisible(false);
      
        
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void menugobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menugobackActionPerformed
      
    }//GEN-LAST:event_menugobackActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        DefaultTableModel model=(DefaultTableModel)tblsearch.getModel();
        int rows=model.getRowCount();
        if(rows>2)
        {
            for(int i=2;i<rows;i++)
            {
                model.removeRow(2);
            }
        }
        try
        {
              Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            ResultSet rs = null;
            Statement stmt = null;
            String query;
             String booksearch=tfsearch.getText();
           switch(combosearchcriteria.getSelectedIndex())
           {    
               case 0:
                    query = "SELECT * FROM book where Book_Title like'%"+(booksearch)+"%'";
                    stmt = con.createStatement();
                    rs = stmt.executeQuery(query);
                       while(rs.next())
            {
                model.addRow(new Object[]
                {
                    rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getDouble(5)});
                }
            System.out.println(rs.getString(1));
                    
                   break;
               case 1: 
                  
                    query = "SELECT * FROM book where Author like'%"+(booksearch)+"%'";
                    stmt = con.createStatement();
                    rs = stmt.executeQuery(query);
                       while(rs.next())
            {
                model.addRow(new Object[]
                {
                    rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getDouble(5)});
                }
            
                   break;
               case 2: 
                   String booktype=(String) combobooktype.getSelectedItem();
                   
                        query = "SELECT * FROM book where Book_Type='"+(booktype)+"'";
                    stmt = con.createStatement();
                    rs = stmt.executeQuery(query);
                       while(rs.next())
            {
                model.addRow(new Object[]
                {
                    rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getDouble(5)});
                }
            
                   break;
               case 3:
                   double minprice=Double.parseDouble(tfminprice.getText());
                   double maxprice=Double.parseDouble(tfmaxprice.getText());
                    query = "SELECT * FROM book where rate between'"+(minprice)+"'and'"+(maxprice)+"'";
                    stmt = con.createStatement();
                    rs = stmt.executeQuery(query);
                       while(rs.next())
            {
                model.addRow(new Object[]
                {
                    rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getDouble(5)});
                }
            
                   break;
                  
           }
         rs.close();
         stmt.close();
         con.close();
        }
        
        catch(Exception e)
        {
                  JOptionPane.showMessageDialog(this,e.getMessage());
        }
       
    }//GEN-LAST:event_btnsearchActionPerformed

    private void combosearchcriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosearchcriteriaActionPerformed
        switch(combosearchcriteria.getSelectedIndex())
        {
            case 0: tfsearch.setVisible(true);
                    combobooktype.setVisible(false);
                    
                    panelprice.setVisible(false);
                    break;
         case 1: tfsearch.setVisible(true);
                    combobooktype.setVisible(false);
                  
                    panelprice.setVisible(false);
                    break; 
             case 2: tfsearch.setVisible(false);
                    combobooktype.setVisible(true);
                    
                    panelprice.setVisible(false);
                    break;
                 case 3: tfsearch.setVisible(false);
                    combobooktype.setVisible(false);
                   
                    panelprice.setVisible(true);
                    break;
            
        }
    }//GEN-LAST:event_combosearchcriteriaActionPerformed

    private void menuexitbookshopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuexitbookshopActionPerformed
          this.setVisible(false);
        new Books_Shop().setVisible(true);
    }//GEN-LAST:event_menuexitbookshopActionPerformed

    private void menusearchbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusearchbookActionPerformed
        IFbookinventory.setVisible(false);
        panelaboutbook.setVisible(false);
        panelsearch.setVisible(true);
        panelsearch.setBounds(10, 150, 800,500);
        IFsearch.setBounds(10, 150, 800,500);
        
    }//GEN-LAST:event_menusearchbookActionPerformed

    private void menuaboutbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuaboutbookActionPerformed
        IFbookinventory.setVisible(false);
        panelsearch.setVisible(false);
        panelaboutbook.setVisible(true);
        panelaboutbook.setBounds(10, 150, 800,500);
        IFaboutbook.setBounds(10, 150, 800,500);
        tfbookid.requestFocus();
    }//GEN-LAST:event_menuaboutbookActionPerformed

    private void menuoldbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuoldbookActionPerformed
       
        panelaboutbook.setVisible(false);
        panelsearch.setVisible(false);
        IFbookinventory.setVisible(true);
        IFbookinventory.setBounds(10, 150, 800,500);
        String username=tfusername.getText();
        DefaultTableModel model=(DefaultTableModel)tblbook.getModel();
        int rows=model.getRowCount();
        if(rows>1)
        {
            for(int i=1;i<rows;i++)
            {
                model.removeRow(1);
            }
        }
        try
        {
              Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            ResultSet rs = null;
            Statement stmt = null;
            String query;
            
        
                    query = "Select * from bookshop where username='"+(username)+"'";
                    stmt = con.createStatement();
                    rs = stmt.executeQuery(query);
                       while(rs.next())
            {
                model.addRow(new Object[]
                {
                    rs.getString(3),rs.getString(4),rs.getDouble(7)});
                }
     
         rs.close();
         stmt.close();
         con.close();
        }
        
        catch(Exception e)
        {
                  JOptionPane.showMessageDialog(this,e.getMessage());
        }
       
    }//GEN-LAST:event_menuoldbookActionPerformed

    private void btnbuybookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuybookActionPerformed
       Double balance=Double.parseDouble(tfbalance.getText());
       String bookid=tfbookid.getText();
       String booktitle=tfbooktitle.getText();
       String author=tfauthor.getText();
       String booktype=tfbooktype.getText();
       Double price=Double.parseDouble(tfprice.getText());
        try
        {
         String username=tfusername.getText();
         
        Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            ResultSet rs=null;
            Statement stmt = con.createStatement();
            
            String query1="Select * from customer where username='"+(username)+"'";
            rs=stmt.executeQuery(query1);
            if(rs.next())
            { 
            if(balance>price)
            {
            String name=rs.getString("Name");
            String query2="Insert into bookshop values('"+(username)+"','"+(name)+"','"+(bookid)+"','"+(booktitle)+"','"+(author)+"','"+(booktype)+"',"+(price)+") "; 
            stmt.executeUpdate(query2);
            balance=balance-price;
            tfbalance.setText(""+balance);
            String query3="Update Customer set Balance="+(balance)+" where username='"+(username)+"'";
            stmt.executeUpdate(query3);
            JOptionPane.showMessageDialog(this,"You have succeesfully bought the book.");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"You can't buy the book as price of book is more than your balance"+"\n"+"You can buy this book by selling other books at Half Price.");
            }
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"You can't buy the book."+"/n"+e.getMessage());
            
        }
            tfbookid.setText("");
            tfbooktitle.setText("");
            tfauthor.setText("");
            tfbooktype.setText("");
            tfprice.setText("");
            lblbookimage.setIcon(new javax.swing.ImageIcon(""));
            
     
    }//GEN-LAST:event_btnbuybookActionPerformed

    private void btnbookdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookdetailsActionPerformed
        String bookid=tfbookid.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            String query = "SELECT * FROM book  WHERE bookidd = '"+(bookid)+"'" ;
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
                
                Double price = rs.getDouble("rate");
                String booktitle=rs.getString("book_title");
                String author=rs.getString("author");
                String booktype=rs.getString("book_type");
                tfprice.setText(""+price);
                tfbooktitle.setText(""+booktitle);
                tfauthor.setText(""+author);
                tfbooktype.setText(""+booktype);
                btnbuybook.setEnabled(true);
                

            }
            else
            {
                JOptionPane.showMessageDialog(this,"Invalid Book_ID");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
         if(bookid.equals("BBB_01"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_01.jpg")));
         }
         else if(bookid.equals("BBB_02"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_02.jpg")));
         }
         else if(bookid.equals("BBB_03"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_03.jpg")));
         }
           else if(bookid.equals("BBB_04"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_04.jpg")));
         }
           else if(bookid.equals("BBB_05"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_05.jpg")));
         }
           else if(bookid.equals("BBB_06"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_06.jpg")));
         }
           else if(bookid.equals("BBB_07"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_07.jpg")));
         }
           else if(bookid.equals("BBB_08"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_08.jpg")));
         }
           else if(bookid.equals("BBB_09"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_09.jpg")));
         }
           else if(bookid.equals("BBB_10"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_10.jpg")));
         }
           else if(bookid.equals("BBB_11"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_11.jpg")));
         }
           else if(bookid.equals("BBB_12"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_12.jpg")));
         }
           else if(bookid.equals("BBB_13"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_13.jpg")));
         }
           else if(bookid.equals("BBB_14"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_14.jpg")));
         }
           else if(bookid.equals("BBB_15"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_15.jpg")));
         }
           else if(bookid.equals("BBB_16"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_16.jpg")));
         }
           else if(bookid.equals("BBB_17"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_17.jpg")));
         }
           else if(bookid.equals("BBB_18"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_18.jpg")));
         }
           else if(bookid.equals("BBB_19"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_19.jpg")));
         }
           else if(bookid.equals("BBB_20"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_20.jpg")));
         }
           else if(bookid.equals("BBB_21"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_21.jpg")));
         }
           else if(bookid.equals("BBB_22"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_22.jpg")));
         }
           else if(bookid.equals("BBB_23"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_23.jpg")));
         }
           else if(bookid.equals("BBB_24"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_24.jpg")));
         }
           else if(bookid.equals("BBB_25"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_25.jpg")));
         }
           else if(bookid.equals("BBB_26"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_26.jpg")));
         }
           else if(bookid.equals("BBB_27"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_27.jpg")));
         }
           else if(bookid.equals("BBB_28"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_28.jpg")));
         }
           else if(bookid.equals("BBB_29"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_29.jpg")));
         }
           else if(bookid.equals("BBB_30"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_30.jpg")));
         }
           else if(bookid.equals("BBB_31"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_31.jpg")));
         }
           else if(bookid.equals("BBB_32"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_32.jpg")));
         }
           else if(bookid.equals("BBB_33"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_33.jpg")));
         }
           else if(bookid.equals("BBB_34"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_34.jpeg")));
         }
           else if(bookid.equals("BBB_36"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_36.jpg")));
         }
           else if(bookid.equals("BBB_37"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_37.jpg")));
         }
           else if(bookid.equals("BBB_38"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_38.jpg")));
         }
           else if(bookid.equals("BBB_39"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_39.jpg")));
         }
           else if(bookid.equals("BBB_40"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_40.jpg")));
         }
           else if(bookid.equals("BBB_41"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_41.jpg")));
         }
           else if(bookid.equals("BBB_42"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_42.jpg")));
         }
           else if(bookid.equals("BBB_43"))
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/BBB_43.jpg")));
         }
           else 
         {
              lblbookimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books/nopreview.png")));
              
         }
    }//GEN-LAST:event_btnbookdetailsActionPerformed

    private void benexitinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benexitinventoryActionPerformed
        IFbookinventory.setVisible(false);
    }//GEN-LAST:event_benexitinventoryActionPerformed

    private void btnsellbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsellbookActionPerformed
        String username=tfusername.getText();
        String sellbookid=tfsellbookid.getText();
        Double balance=Double.parseDouble(tfbalance.getText());
        try
        {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            String query = "SELECT * FROM bookshop  WHERE book_id = '"+(sellbookid)+"'and username='"+(username)+"'" ;
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {

                Double originalprice = rs.getDouble("price");
                String sellbooktitle=rs.getString("book_title");
                Double sellprice=originalprice/2;
                balance=balance+sellprice;
                tfselloriginalprice.setText(""+originalprice);
                tfsellprice.setText(""+sellprice);
                tfsellbalance.setText(""+balance);
                tfbalance.setText(""+balance);
                tfsellbooktitle.setText(""+sellbooktitle);
                String query2="Delete from bookshop where username='"+(username)+"'and book_id='"+(sellbookid)+"'";
                stmt.executeUpdate(query2);
                String query3="Update Customer set Balance="+(balance)+" where username='"+(username)+"'";
                stmt.executeUpdate(query3);
                JOptionPane.showMessageDialog(this,"This book have been sold succeesfully");
                tfsellbookid.setText("");
                tfselloriginalprice.setText("");
                tfsellprice.setText("");
                tfsellbalance.setText("");
                tfsellbooktitle.setText("");

            }
            else
            {
                JOptionPane.showMessageDialog(this,"You don't have the book with this Book_ID");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btnsellbookActionPerformed

    private void tfsellbookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsellbookidActionPerformed
        String username=tfusername.getText();
        String sellbookid=tfsellbookid.getText();
        
        Double balance=Double.parseDouble(tfbalance.getText());
        try
        {
          
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            String query = "SELECT * FROM bookshop  WHERE book_id = '"+(sellbookid)+"'and username='"+(username)+"'" ;
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
                String sellbooktitle=rs.getString("book_title");
                Double originalprice = rs.getDouble("price");
                Double sellprice=originalprice/2;
                Double totalbalance=balance+sellprice;
                tfselloriginalprice.setText(""+originalprice);
                tfsellprice.setText(""+sellprice);
                tfsellbalance.setText(""+totalbalance);
                tfsellbooktitle.setText(""+sellbooktitle);
                
              
            }
            else
            {
                JOptionPane.showMessageDialog(this,"You don't have the book with this Book_ID");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
            
    }//GEN-LAST:event_tfsellbookidActionPerformed

    private void btndontsellbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndontsellbookActionPerformed
                tfsellbookid.setText("");
                tfselloriginalprice.setText("");
                tfsellprice.setText("");
                tfsellbalance.setText("");
                tfsellbooktitle.setText("");
    }//GEN-LAST:event_btndontsellbookActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
         DefaultTableModel model=(DefaultTableModel)tblsearch.getModel();
        int rows=model.getRowCount();
        if(rows>2)
        {
            for(int i=2;i<rows;i++)
            {
                model.removeRow(2);
            }
        } 
        tfsearch.setText("");
        tfsearch.setVisible(false);
        panelprice.setVisible(false);
        tfminprice.setText("");
        tfmaxprice.setText("");
        combobooktype.setVisible(false);
    }//GEN-LAST:event_btnclearActionPerformed

    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusernameActionPerformed
         pfpassword.requestFocus();        
    }//GEN-LAST:event_tfusernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame IFaboutbook;
    private javax.swing.JInternalFrame IFbookinventory;
    private javax.swing.JInternalFrame IFsearch;
    private javax.swing.JButton benexitinventory;
    private javax.swing.JButton btnbookdetails;
    private javax.swing.JButton btnbuybook;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndontsellbook;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsellbook;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox combobooktype;
    private javax.swing.JComboBox combosearchcriteria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblbalance;
    private javax.swing.JLabel lblbookimage;
    private javax.swing.JLabel lbliconbookshop;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JMenuItem menuaboutbook;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenu menubook;
    private javax.swing.JMenuItem menuexitbookshop;
    private javax.swing.JMenu menugoback;
    private javax.swing.JMenuItem menuoldbook;
    private javax.swing.JMenuItem menusearchbook;
    private javax.swing.JScrollPane panelaboutbook;
    private javax.swing.JPanel panellogin;
    private javax.swing.JPanel panelprice;
    private javax.swing.JScrollPane panelsearch;
    private javax.swing.JPanel panelsellbook;
    private javax.swing.JPasswordField pfpassword;
    private javax.swing.JTable tblbook;
    private javax.swing.JTable tblsearch;
    private javax.swing.JTextField tfauthor;
    private javax.swing.JTextField tfbalance;
    private javax.swing.JTextField tfbookid;
    private javax.swing.JTextField tfbooktitle;
    private javax.swing.JTextField tfbooktype;
    private javax.swing.JTextField tfmaxprice;
    private javax.swing.JTextField tfminprice;
    private javax.swing.JTextField tfprice;
    private javax.swing.JTextField tfsearch;
    private javax.swing.JTextField tfsellbalance;
    private javax.swing.JTextField tfsellbookid;
    private javax.swing.JTextField tfsellbooktitle;
    private javax.swing.JTextField tfselloriginalprice;
    private javax.swing.JTextField tfsellprice;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
