
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Micronet
 */
public class Books_Shop extends javax.swing.JFrame {

    /**
     * Creates new form Books_Shop
     */
    public Books_Shop() {
        initComponents();
        panellift.setVisible(false);
        panelbook.setVisible(false);
         this.setIconImage(new ImageIcon(getClass().getResource("/Images/orchid_books_shop.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnlift = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelbook = new javax.swing.JPanel();
        btnbookyes = new javax.swing.JButton();
        btnbookno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panellift = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        combolift = new javax.swing.JComboBox();
        btnliftgo = new javax.swing.JButton();
        btnliftcancel = new javax.swing.JButton();
        btnbookshop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.orange);

        btnlift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/elevator.jpg"))); // NOI18N
        btnlift.setText("jButton1");
        btnlift.setOpaque(false);
        btnlift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnliftActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("I Floor : Orchid Books Shop");

        panelbook.setBackground(new java.awt.Color(204, 204, 255));
        panelbook.setForeground(new java.awt.Color(0, 102, 204));

        btnbookyes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbookyes.setText("YES");
        btnbookyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookyesActionPerformed(evt);
            }
        });

        btnbookno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbookno.setText("NO");
        btnbookno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbooknoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Do you want to go to Book Shop ?");

        javax.swing.GroupLayout panelbookLayout = new javax.swing.GroupLayout(panelbook);
        panelbook.setLayout(panelbookLayout);
        panelbookLayout.setHorizontalGroup(
            panelbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbookLayout.createSequentialGroup()
                .addGroup(panelbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbookLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnbookyes)
                        .addGap(43, 43, 43)
                        .addComponent(btnbookno))
                    .addGroup(panelbookLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelbookLayout.setVerticalGroup(
            panelbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbookLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbookyes)
                    .addComponent(btnbookno))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panellift.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel4.setText("Go To ");

        combolift.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combolift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ground    :   Parking Lot", "I Floor     :   Books Shop", "II Floor    :   Restaurant", "III Floor   :   Cinema Hall", "IV Floor    :   Casino" }));

        btnliftgo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnliftgo.setText("Go To Floor");
        btnliftgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnliftgoActionPerformed(evt);
            }
        });

        btnliftcancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnliftcancel.setText("Cancel");
        btnliftcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnliftcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelliftLayout = new javax.swing.GroupLayout(panellift);
        panellift.setLayout(panelliftLayout);
        panelliftLayout.setHorizontalGroup(
            panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelliftLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelliftLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combolift, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelliftLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnliftgo)
                        .addGap(32, 32, 32)
                        .addComponent(btnliftcancel)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        panelliftLayout.setVerticalGroup(
            panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelliftLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combolift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnliftgo)
                    .addComponent(btnliftcancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnbookshop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orchid_books_shop.jpg"))); // NOI18N
        btnbookshop.setText("jButton1");
        btnbookshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookshopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(panelbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnbookshop, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnlift, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(panellift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlift, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbookshop, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panellift, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelbook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnliftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnliftActionPerformed
        panellift.setVisible(true);
    }//GEN-LAST:event_btnliftActionPerformed

    private void btnbooknoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbooknoActionPerformed
          panelbook.setVisible(false);
    }//GEN-LAST:event_btnbooknoActionPerformed

    private void btnbookshopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookshopActionPerformed
        panelbook.setVisible(true);
    }//GEN-LAST:event_btnbookshopActionPerformed

    private void btnliftgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnliftgoActionPerformed
           switch(combolift.getSelectedIndex())
       {
           case 0: this.setVisible(false);
                new Parking().setVisible(true);
                 break;
           case 1: this.setVisible(false);
                new Books_Shop().setVisible(true);
                 break;
           case 2: this.setVisible(false);
                new Restaurant().setVisible(true);
                 break;
           case 3: this.setVisible(false);
                new Cinema_Hall().setVisible(true);
                 break;
           case 4: this.setVisible(false);
                new Casino().setVisible(true);
                 break;
         
       }        
    }//GEN-LAST:event_btnliftgoActionPerformed

    private void btnliftcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnliftcancelActionPerformed
        panellift.setVisible(false);
    }//GEN-LAST:event_btnliftcancelActionPerformed

    private void btnbookyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookyesActionPerformed
        this.setVisible(false);
        new Book().setVisible(true);
    }//GEN-LAST:event_btnbookyesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books_Shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbookno;
    private javax.swing.JButton btnbookshop;
    private javax.swing.JButton btnbookyes;
    private javax.swing.JButton btnlift;
    private javax.swing.JButton btnliftcancel;
    private javax.swing.JButton btnliftgo;
    private javax.swing.JComboBox combolift;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelbook;
    private javax.swing.JPanel panellift;
    // End of variables declaration//GEN-END:variables
}
