
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Micronet
 */
public class Cinema_Hall extends javax.swing.JFrame {

    /**
     * Creates new form Cinema_Hall
     */
    public Cinema_Hall() {
        initComponents();
        panellift.setVisible(false);
        panelcinema.setVisible(false);
          this.setIconImage(new ImageIcon(getClass().getResource("/Images/A8.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncinema = new javax.swing.JButton();
        btnlift = new javax.swing.JButton();
        panellift = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        combolift = new javax.swing.JComboBox();
        btnliftgo = new javax.swing.JButton();
        btnliftcancel = new javax.swing.JButton();
        panelcinema = new javax.swing.JPanel();
        btncinemayes = new javax.swing.JButton();
        btncinemano = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btncinema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/A8.jpg"))); // NOI18N
        btncinema.setText("jButton1");
        btncinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncinemaActionPerformed(evt);
            }
        });

        btnlift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/elevator.jpg"))); // NOI18N
        btnlift.setText("jButton1");
        btnlift.setOpaque(false);
        btnlift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnliftActionPerformed(evt);
            }
        });

        panellift.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel4.setText("Go To ");

        combolift.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combolift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ground    :   Parking Lot", "I Floor     :   Books Shop", "II Floor    :   Restaurant", "III Floor   :   Cinema Hall", "IV Floor    :   Casino" }));

        btnliftgo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnliftgo.setText("Go To Floor");
        btnliftgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnliftgoActionPerformed(evt);
            }
        });

        btnliftcancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnliftcancel.setText("Cancel");
        btnliftcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnliftcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelliftLayout = new javax.swing.GroupLayout(panellift);
        panellift.setLayout(panelliftLayout);
        panelliftLayout.setHorizontalGroup(
            panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelliftLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelliftLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combolift, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelliftLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnliftgo)
                        .addGap(32, 32, 32)
                        .addComponent(btnliftcancel)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelliftLayout.setVerticalGroup(
            panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelliftLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combolift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnliftgo)
                    .addComponent(btnliftcancel))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelcinema.setBackground(new java.awt.Color(255, 51, 51));
        panelcinema.setForeground(new java.awt.Color(0, 102, 204));

        btncinemayes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncinemayes.setText("YES");
        btncinemayes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncinemayesActionPerformed(evt);
            }
        });

        btncinemano.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncinemano.setText("NO");
        btncinemano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncinemanoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Do you want to go to Cinema Hall ?");

        javax.swing.GroupLayout panelcinemaLayout = new javax.swing.GroupLayout(panelcinema);
        panelcinema.setLayout(panelcinemaLayout);
        panelcinemaLayout.setHorizontalGroup(
            panelcinemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcinemaLayout.createSequentialGroup()
                .addGroup(panelcinemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcinemaLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btncinemayes)
                        .addGap(43, 43, 43)
                        .addComponent(btncinemano))
                    .addGroup(panelcinemaLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panelcinemaLayout.setVerticalGroup(
            panelcinemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcinemaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelcinemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncinemayes)
                    .addComponent(btncinemano))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("III Floor : Cinema Hall");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btncinema, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlift, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(panelcinema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panellift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncinema, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlift, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelcinema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panellift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnliftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnliftActionPerformed
        panellift.setVisible(true);
    }//GEN-LAST:event_btnliftActionPerformed

    private void btncinemanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncinemanoActionPerformed
        panelcinema.setVisible(false);         
    }//GEN-LAST:event_btncinemanoActionPerformed

    private void btncinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncinemaActionPerformed
        panelcinema.setVisible(true);
    }//GEN-LAST:event_btncinemaActionPerformed

    private void btnliftgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnliftgoActionPerformed
         switch(combolift.getSelectedIndex())
       {
           case 0: this.setVisible(false);
                new Parking().setVisible(true);
                 break;
           case 1: this.setVisible(false);
                new Books_Shop().setVisible(true);
                 break;
           case 2: this.setVisible(false);
                new Restaurant().setVisible(true);
                 break;
           case 3: this.setVisible(false);
                new Cinema_Hall().setVisible(true);
                 break;
           case 4: this.setVisible(false);
                new Casino().setVisible(true);
                 break;
         
       }        
    }//GEN-LAST:event_btnliftgoActionPerformed

    private void btnliftcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnliftcancelActionPerformed
        panellift.setVisible(false);
    }//GEN-LAST:event_btnliftcancelActionPerformed

    private void btncinemayesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncinemayesActionPerformed
        this.setVisible(false);
        new Movie().setVisible(true);
    }//GEN-LAST:event_btncinemayesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cinema_Hall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cinema_Hall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cinema_Hall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cinema_Hall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cinema_Hall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncinema;
    private javax.swing.JButton btncinemano;
    private javax.swing.JButton btncinemayes;
    private javax.swing.JButton btnlift;
    private javax.swing.JButton btnliftcancel;
    private javax.swing.JButton btnliftgo;
    private javax.swing.JComboBox combolift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelcinema;
    private javax.swing.JPanel panellift;
    // End of variables declaration//GEN-END:variables
}
