import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Micronet
 */
public class CustomerDetails extends javax.swing.JFrame {

    /**
     * Creates new form CustomerDetails
     */
    public CustomerDetails() {
        initComponents();
         this.setIconImage(new ImageIcon(getClass().getResource("/Images/open letter.jpg")).getImage());
         tfusername.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pfpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        tfmobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        combocreditcard = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tacreditcard = new javax.swing.JTextArea();
        btnsubmit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btngoback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User Name");

        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        pfpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfpasswordActionPerformed(evt);
            }
        });

        jLabel4.setText("Mobile No.");

        tfmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmobileActionPerformed(evt);
            }
        });

        jLabel5.setText("Membership Card Type");

        combocreditcard.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combocreditcard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Platinum", "Gold", "Silver" }));
        combocreditcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocreditcardActionPerformed(evt);
            }
        });

        tacreditcard.setColumns(20);
        tacreditcard.setRows(5);
        jScrollPane1.setViewportView(tacreditcard);

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel6.setText("Customer Information");

        btngoback.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btngoback.setText("Go Back");
        btngoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngobackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfusername)
                    .addComponent(tfname)
                    .addComponent(pfpassword)
                    .addComponent(tfmobile)
                    .addComponent(combocreditcard, 0, 232, Short.MAX_VALUE))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnsubmit)
                        .addGap(52, 52, 52)
                        .addComponent(btngoback)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combocreditcard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsubmit)
                    .addComponent(btngoback))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combocreditcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocreditcardActionPerformed
    switch(combocreditcard.getSelectedIndex())
    {
        case 0: tacreditcard.setText("Platinum Credit Card have 15000 Rs. in Account Initially"+"\n"+" But you can't enjoy Casino.");
                 break;
        case 1: tacreditcard.setText("Gold Credit Card have 10000 Rs. in Account Initially"+"\n"+" But you can't enjoy Restaurant.");
                 break;
        case 2: tacreditcard.setText("Silver Credit Card have 5000 Rs. in Account Initially"+"\n"+" And you can enjoy all 4 places.");
                 break;
    }
    }//GEN-LAST:event_combocreditcardActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
             try
     {
         Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
       ResultSet rs=null;
      
        Statement stmt=con.createStatement();
           
         String username=tfusername.getText();
         String name=tfname.getText();
         String password=pfpassword.getText();
         String mobile=tfmobile.getText();
         String card=(String) combocreditcard.getSelectedItem();
         Double balance = null;
         switch(combocreditcard.getSelectedIndex())
         {
             case 0: balance=15000.00;
                 break;
             case 1: balance=10000.00;
                 break;
             case 2: balance=5000.00;
                 break;
             default: JOptionPane.showMessageDialog(this,"Please Select Credit Card Type");
         }
        
        
         
             stmt.executeUpdate("Insert into customer values('"+(username)+"','"+(name)+"','"+(password)+"','"+(mobile)+"','"+(card)+"',"+(balance)+")");
         JOptionPane.showMessageDialog(this," You have been added as a regular customer"+"\n"+"Now,you can enter the Boom Boom mall"+"\n"+"Click Go Back Button and Select Existing Customer.");
         
         rs.close();
         stmt.close();
         con.close();
         
         }
     
             catch(Exception e)
             {
                 JOptionPane.showMessageDialog(this,e.getMessage());
                 tfusername.setText("");
                 tfname.setText("");
                 pfpassword.setText("");
                 tfmobile.setText("");
                 
             
             }      
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btngobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngobackActionPerformed
         new Start().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_btngobackActionPerformed

    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusernameActionPerformed
        tfname.requestFocus();
    }//GEN-LAST:event_tfusernameActionPerformed

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        pfpassword.requestFocus();
    }//GEN-LAST:event_tfnameActionPerformed

    private void pfpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfpasswordActionPerformed
        tfmobile.requestFocus();
    }//GEN-LAST:event_pfpasswordActionPerformed

    private void tfmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmobileActionPerformed
        combocreditcard.requestFocus();
        
    }//GEN-LAST:event_tfmobileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngoback;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox combocreditcard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField pfpassword;
    private javax.swing.JTextArea tacreditcard;
    private javax.swing.JTextField tfmobile;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
