
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
//import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Micronet
 */
public class Customer_Department extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Department
     */
    public Customer_Department() {
        initComponents();
       
        panelactivity.setVisible(false);
       
        panelcustomer.setVisible(false);
        //this.setIconImage(new ImageIcon(getClass().getResource("/Manager/boomboom19.jpg")).getImage());
            
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelcustomer = new javax.swing.JScrollPane();
        IFcustomer = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfcard = new javax.swing.JTextField();
        tfmobile = new javax.swing.JTextField();
        tfbalance = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnactivity = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelactivity = new javax.swing.JScrollPane();
        IFactivity = new javax.swing.JInternalFrame();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfnameact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfusernameact = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfrestaurant = new javax.swing.JTextField();
        tfbookshop = new javax.swing.JTextField();
        tfcasino = new javax.swing.JTextField();
        tfcinema = new javax.swing.JTextField();
        comboactivity = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        customerdepartment = new javax.swing.JMenu();
        CustomerMenu = new javax.swing.JMenuItem();
        menuexitdepartment = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IFcustomer.setVisible(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setText("Enter Username");

        tfusername.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setText("Mobile");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setText("Card");

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel6.setText("Balance");

        tfname.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        tfcard.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        tfmobile.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        tfbalance.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnupdate.setText("Update Customer Record");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btndelete.setText("Delete Customer Record");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnactivity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnactivity.setText("Show Customer Activity");
        btnactivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactivityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IFcustomerLayout = new javax.swing.GroupLayout(IFcustomer.getContentPane());
        IFcustomer.getContentPane().setLayout(IFcustomerLayout);
        IFcustomerLayout.setHorizontalGroup(
            IFcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFcustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(IFcustomerLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(IFcustomerLayout.createSequentialGroup()
                .addGroup(IFcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFcustomerLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(IFcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113)
                        .addGroup(IFcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcard, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(IFcustomerLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnupdate)
                        .addGap(46, 46, 46)
                        .addComponent(btndelete)
                        .addGap(42, 42, 42)
                        .addComponent(btnactivity)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IFcustomerLayout.setVerticalGroup(
            IFcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFcustomerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(IFcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(IFcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(IFcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(IFcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(IFcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(IFcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btnactivity))
                .addGap(91, 91, 91))
        );

        panelcustomer.setViewportView(IFcustomer);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("CUSTOMER DEPARTMENT");

        IFactivity.setVisible(true);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText(" CUSTOMER's ACTIVITY");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel8.setText("Customer Name");

        tfnameact.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel9.setText("Username");

        tfusernameact.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel10.setText("No.of Books bought");

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel11.setText("No.of Movies watched");

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel12.setText("No.of Restaurant visits");

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel13.setText("No.of Times Gambled");

        tfrestaurant.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        tfbookshop.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        tfcasino.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        tfcinema.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        comboactivity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comboactivity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Show Customer Activity", "Show Customer's Money Activity" }));
        comboactivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboactivityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IFactivityLayout = new javax.swing.GroupLayout(IFactivity.getContentPane());
        IFactivity.getContentPane().setLayout(IFactivityLayout);
        IFactivityLayout.setHorizontalGroup(
            IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(IFactivityLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addGap(43, 43, 43)
                .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfbookshop, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfrestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfcinema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfcasino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 134, Short.MAX_VALUE))
            .addGroup(IFactivityLayout.createSequentialGroup()
                .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFactivityLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel7))
                    .addGroup(IFactivityLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfnameact, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addComponent(tfusernameact))
                        .addGap(28, 28, 28)
                        .addComponent(comboactivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        IFactivityLayout.setVerticalGroup(
            IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFactivityLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFactivityLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfusernameact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IFactivityLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboactivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfnameact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfbookshop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(22, 22, 22)
                .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfrestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfcinema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(IFactivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfcasino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        panelactivity.setViewportView(IFactivity);

        customerdepartment.setText("Customer Department");

        CustomerMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        CustomerMenu.setText("Customer Menu");
        CustomerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerMenuActionPerformed(evt);
            }
        });
        customerdepartment.add(CustomerMenu);

        menuexitdepartment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.SHIFT_MASK));
        menuexitdepartment.setText("Exit Department");
        menuexitdepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuexitdepartmentActionPerformed(evt);
            }
        });
        customerdepartment.add(menuexitdepartment);

        jMenuBar1.add(customerdepartment);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panelactivity, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelactivity, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(498, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        String username=tfusername.getText();  
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            ResultSet rs = null;
            Statement stmt = null;
           
            String query="Delete from customer where username='"+(username)+"'";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this,"Customer record deleted succeesfully.");
            tfname.setText("");
            tfmobile.setText("");
            tfcard.setText("");
            tfbalance.setText("");
        }
             catch(Exception e)
             {
                 JOptionPane.showMessageDialog(this,"Customer record can't be deleted"+"\n"+e.getMessage());
             }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusernameActionPerformed
        String username=tfusername.getText();
       
       


        String query = "SELECT * FROM customer WHERE Username = '" + (username)+"'" ;
        try {
          
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
          
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
          
                String name = rs.getString("name");
                String card=rs.getString("card");
                double balance=rs.getDouble("balance");
                String mobile=rs.getString("mobile");
               
                tfmobile.setText(""+mobile);      
                tfname.setText(""+name);
                tfcard.setText(""+card);
                tfbalance.setText(""+balance);
              
               
             
                con.close();
                stmt.close();
                rs.close();
               
            }
            else 
            {
                JOptionPane.showMessageDialog(null, "Invalid Username");
                tfusername.setText("");
              
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }   
    }//GEN-LAST:event_tfusernameActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
                 try
     {
         Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
       ResultSet rs=null;
      
        Statement stmt=con.createStatement();
           
         String username=tfusername.getText();
         String name=tfname.getText();
         String balance=tfbalance.getText();
         String mobile=tfmobile.getText();
         String card=tfcard.getText();
         String query1="Update customer set name='"+(name)+"' where username='"+(username)+"'";
         String query2="Update customer set mobile='"+(mobile)+"' where username='"+(username)+"'";
         String query3="Update customer set card='"+(card)+"' where username='"+(username)+"'";
         String query4="Update customer set balance="+(balance)+" where username='"+(username)+"'";
         stmt.executeUpdate(query1);
         stmt.executeUpdate(query2);
         stmt.executeUpdate(query3);
         stmt.executeUpdate(query4);
        
         
             
         JOptionPane.showMessageDialog(this,"Customer Record updated succeesfuly.");
         
         rs.close();
         stmt.close();
         con.close();
         
         }
     
             catch(Exception e)
             {
                 JOptionPane.showMessageDialog(this,e.getMessage());
                
                 
             
             }      
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnactivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactivityActionPerformed
        panelcustomer.setVisible(false);      
        panelactivity.setVisible(true);
        panelactivity.setBounds(10,50,1000,600);
        IFactivity.setBounds(10,50,1000,600);
              String username=tfusername.getText();
              String name=tfname.getText();
              tfusernameact.setText(""+username);
              tfnameact.setText(""+name);
   
    }//GEN-LAST:event_btnactivityActionPerformed

    private void comboactivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboactivityActionPerformed
        String username=tfusername.getText();
        switch(comboactivity.getSelectedIndex())
        {
            case 0: 
            try
     {
         Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
       ResultSet rs=null;
      
        Statement stmt=con.createStatement();
           
        
          
         String query1="Select * from bookshop where username='"+(username)+"'";
         String query2="Select * from restaurant where username='"+(username)+"'";
         String query3="Select * from cinema where username='"+(username)+"'";
         String query4="Select * from casino where username='"+(username)+"'";
          int bookshop=0,restaurant=0,cinema=0,casino=0;
            ResultSet  rs1=stmt.executeQuery(query1);
              while(rs1.next())
              {
                 bookshop++; 
              }
             tfbookshop.setText(""+bookshop);
             jLabel10.setText("No. of Books Bought");
            ResultSet rs2=stmt.executeQuery(query2);
               while(rs2.next())
         {
              restaurant++;
             
         }
              tfrestaurant.setText(""+restaurant);
              jLabel12.setText("No. of Restaurant visits");
            ResultSet rs3=stmt.executeQuery(query3);
                  while(rs3.next())
        {
             cinema++;
        }
             tfcinema.setText(""+cinema);
             jLabel11.setText("No. of movies watched");
            ResultSet rs4=stmt.executeQuery(query4);
              
         while(rs4.next())
         {
             casino++;
         }
             tfcasino.setText(""+casino);  
             jLabel13.setText("No. of times Gambled");
         }
     
             catch(Exception e)
             {
                 JOptionPane.showMessageDialog(this,e.getMessage());
                
                 
             }
                break;
            case 1: 
          try
     {
         Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
       ResultSet rs=null;
      
        Statement stmt=con.createStatement();
           
        
          
         String query1="Select * from bookshop where username='"+(username)+"'";
         String query2="Select * from restaurant where username='"+(username)+"'";
         String query3="Select * from cinema where username='"+(username)+"'";
         String query4="Select * from casino where username='"+(username)+"'";
          double bookshop=0,restaurant=0,cinema=0,casino=0;
            ResultSet  rs1=stmt.executeQuery(query1);
              while(rs1.next())
              {
                  Double price=rs1.getDouble("Price");
                  bookshop=bookshop+price;
              }
             tfbookshop.setText(""+bookshop);
             jLabel10.setText("Money Spent in Bookshop");
            ResultSet rs2=stmt.executeQuery(query2);
               while(rs2.next())
         {
             Double bill=rs2.getDouble("Bill");
             restaurant=restaurant+bill;
             
         }
              tfrestaurant.setText(""+restaurant);
              jLabel12.setText("Money Spent in Restaurant");
            ResultSet rs3=stmt.executeQuery(query3);
                  while(rs3.next())
        {
            Double bill=rs3.getDouble("Bill");
            cinema=cinema+bill;
        }
             tfcinema.setText(""+cinema);
             jLabel11.setText("Money Spent in Cinema Hall");
            ResultSet rs4=stmt.executeQuery(query4);
              
         while(rs4.next())
         {
             Double money=rs4.getDouble("Money_Difference");
             casino=casino+money;
         }
         if(casino>0)
         {
             
             tfcasino.setText(" Profit : "+casino);  
         }
         else if(casino<0)
         {
             tfcasino.setText(" Loss : "+(0-casino));
         }
         else
         {
             tfcasino.setText("No Profit,No Loss.");
         }
          jLabel13.setText("Money Gambling in Casino");
         }
             
             catch(Exception e)
             {
                 JOptionPane.showMessageDialog(this,e.getMessage());
                
                 
             }
                break;
        }
    }//GEN-LAST:event_comboactivityActionPerformed

    private void menuexitdepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuexitdepartmentActionPerformed
             this.setVisible(false);
             new Manager1().setVisible(true);
    }//GEN-LAST:event_menuexitdepartmentActionPerformed

    private void CustomerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerMenuActionPerformed
        panelcustomer.setVisible(true);      
        panelactivity.setVisible(false);
        panelcustomer.setBounds(10,50,1000,600);
        IFcustomer.setBounds(10,50,1000,600);
    }//GEN-LAST:event_CustomerMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Department().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CustomerMenu;
    private javax.swing.JInternalFrame IFactivity;
    private javax.swing.JInternalFrame IFcustomer;
    private javax.swing.JButton btnactivity;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox comboactivity;
    private javax.swing.JMenu customerdepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem menuexitdepartment;
    private javax.swing.JScrollPane panelactivity;
    private javax.swing.JScrollPane panelcustomer;
    private javax.swing.JTextField tfbalance;
    private javax.swing.JTextField tfbookshop;
    private javax.swing.JTextField tfcard;
    private javax.swing.JTextField tfcasino;
    private javax.swing.JTextField tfcinema;
    private javax.swing.JTextField tfmobile;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfnameact;
    private javax.swing.JTextField tfrestaurant;
    private javax.swing.JTextField tfusername;
    private javax.swing.JTextField tfusernameact;
    // End of variables declaration//GEN-END:variables
}
