
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Micronet
 */
public class Food extends javax.swing.JFrame {

    /**
     * Creates new form Food
     */
    public Food() {
        initComponents();
       tfdessert.setText("0");
       tfveg.setText("0");
       tfnonveg.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Des = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        veg = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        nveg = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        Exit = new javax.swing.JFrame();
        jButton15 = new javax.swing.JButton();
        DesL = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList();
        a1 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        vegL = new javax.swing.JFrame();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        a2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList();
        jLabel26 = new javax.swing.JLabel();
        nvegL = new javax.swing.JFrame();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        list3 = new javax.swing.JList();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        a3 = new javax.swing.JTextField();
        F4 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        btndessert = new javax.swing.JButton();
        btnveg = new javax.swing.JButton();
        btnnonveg = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfbalance = new javax.swing.JTextField();
        tfmobile = new javax.swing.JTextField();
        tfdessert = new javax.swing.JTextField();
        tfveg = new javax.swing.JTextField();
        tfnonveg = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tftotalpayment = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfdiscount = new javax.swing.JTextField();
        btndesserttotal = new javax.swing.JButton();
        btnvegtotal = new javax.swing.JButton();
        btnnonvegtotal = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnbill = new javax.swing.JButton();
        btnorder = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        tfnetbill = new javax.swing.JTextField();
        panellogin2 = new javax.swing.JPanel();
        lblusername2 = new javax.swing.JLabel();
        tfusername2 = new javax.swing.JTextField();
        pfpassword2 = new javax.swing.JPasswordField();
        lblpassword2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnsubmit2 = new javax.swing.JButton();

        Des.setTitle("Dessert Menu");
        Des.setIconImage(new ImageIcon(getClass().getResource("1 (106).jpg")).getImage());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food/menu3.jpg"))); // NOI18N

        javax.swing.GroupLayout DesLayout = new javax.swing.GroupLayout(Des.getContentPane());
        Des.getContentPane().setLayout(DesLayout);
        DesLayout.setHorizontalGroup(
            DesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DesLayout.setVerticalGroup(
            DesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        veg.setTitle("Veg Menu");
        veg.setIconImage(new ImageIcon(getClass().getResource("1 (106).jpg")).getImage());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food/08 Indian Veg Gravy.JPG"))); // NOI18N

        javax.swing.GroupLayout vegLayout = new javax.swing.GroupLayout(veg.getContentPane());
        veg.getContentPane().setLayout(vegLayout);
        vegLayout.setHorizontalGroup(
            vegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vegLayout.setVerticalGroup(
            vegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        nveg.setTitle("Non Veg Menu");
        nveg.setIconImage(new ImageIcon(getClass().getResource("1 (106).jpg")).getImage());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food/10 Indian Non Veg Gravy.JPG"))); // NOI18N

        javax.swing.GroupLayout nvegLayout = new javax.swing.GroupLayout(nveg.getContentPane());
        nveg.getContentPane().setLayout(nvegLayout);
        nvegLayout.setHorizontalGroup(
            nvegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        nvegLayout.setVerticalGroup(
            nvegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Exit.setTitle("Exit");
        Exit.setIconImage(new ImageIcon(getClass().getResource("1 (106).jpg")).getImage());

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food/restaurant-interiors-pictures.jpg"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExitLayout = new javax.swing.GroupLayout(Exit.getContentPane());
        Exit.getContentPane().setLayout(ExitLayout);
        ExitLayout.setHorizontalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ExitLayout.setVerticalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        DesL.setTitle("Dessert Total");
        DesL.setIconImage(new ImageIcon(getClass().getResource("1 (106).jpg")).getImage());

        list1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Tarte Aux Pacanes", "Tarte à la Maringe au citron", "Pizza glacee et son coilis", "Creme glacee", "Extra Creme glacee", "Gateau aux carotte Elite", "Gateau au formage a la new-yorkaise", "Gateau au fudge chaud", "Gateau au chocol et framboises", "Tarte caramel et choclate malte", "Gateau formage aux pacanes t au caramel", "Tarte aux pommes epassie", "Tarte aux fruits de la foret", " ", " ", " ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list1);

        a1.setEditable(false);
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });

        jButton14.setText("DONE");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton13.setText("CALCULATE");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food/12.jpg"))); // NOI18N

        javax.swing.GroupLayout DesLLayout = new javax.swing.GroupLayout(DesL.getContentPane());
        DesL.getContentPane().setLayout(DesLLayout);
        DesLLayout.setHorizontalGroup(
            DesLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesLLayout.createSequentialGroup()
                .addGroup(DesLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DesLLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DesLLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(DesLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(DesLLayout.createSequentialGroup()
                                .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addGap(40, 40, 40))
        );
        DesLLayout.setVerticalGroup(
            DesLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesLLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DesLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13))
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(DesLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        vegL.setTitle("Veg Total");
        vegL.setIconImage(new ImageIcon(getClass().getResource("1 (106).jpg")).getImage());

        jButton16.setText("CALCULATE");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("DONE");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        a2.setEditable(false);

        list2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Subz Handi", "Dum ki Gobi", "Corn Capsium", "Lucknowi Kofta", "Dingri mutter Harapyaz", "Vg makhan wala", "Channa masala", "Navarthna Korma", "Methi mutter wali", "Bhindi Masala", "Baigan bharta", "Dum aloo Kashmiri", "Stuffed capsicum Masala   ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(list2);

        javax.swing.GroupLayout vegLLayout = new javax.swing.GroupLayout(vegL.getContentPane());
        vegL.getContentPane().setLayout(vegLLayout);
        vegLLayout.setHorizontalGroup(
            vegLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vegLLayout.createSequentialGroup()
                .addGroup(vegLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vegLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(vegLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(vegLLayout.createSequentialGroup()
                                .addComponent(jButton16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(vegLLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        vegLLayout.setVerticalGroup(
            vegLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vegLLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(vegLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(vegLLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton16))
                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton17)
                .addGap(48, 48, 48))
            .addGroup(vegLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        nvegL.setTitle("Non Veg Total");
        nvegL.setIconImage(new ImageIcon(getClass().getResource("1 (106).jpg")).getImage());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food/Appam-and-Mutta-Curry.jpg"))); // NOI18N

        list3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Dhanya Murgh", "Muragh Peshawari", "Murh Handi", "Kadai Chicken", "Chicken Hydrabadi", "Chicken Mughlai", "Chicken Tikka Masala", "Chicken Butter Masala", "Chicken Dopiaza", "Murgh Patiyala", "Laal Maas", "Gosht Khada Masala", "Dum ki Gosht " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(list3);

        jButton18.setText("CALCULATE");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("DONE");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        a3.setEditable(false);

        javax.swing.GroupLayout nvegLLayout = new javax.swing.GroupLayout(nvegL.getContentPane());
        nvegL.getContentPane().setLayout(nvegLLayout);
        nvegLLayout.setHorizontalGroup(
            nvegLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nvegLLayout.createSequentialGroup()
                .addGroup(nvegLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nvegLLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(nvegLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(nvegLLayout.createSequentialGroup()
                                .addComponent(jButton18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(nvegLLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        nvegLLayout.setVerticalGroup(
            nvegLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nvegLLayout.createSequentialGroup()
                .addGroup(nvegLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nvegLLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(nvegLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton19))
                    .addGroup(nvegLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        F4.setTitle("Customer Detail");
        F4.setIconImage(new ImageIcon(getClass().getResource("1 (106).jpg")).getImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "MENU CARDS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("814yzx", 0, 14), new java.awt.Color(102, 51, 0))); // NOI18N

        btndessert.setText("DESSERTS");
        btndessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndessertActionPerformed(evt);
            }
        });

        btnveg.setText("VEG.");
        btnveg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvegActionPerformed(evt);
            }
        });

        btnnonveg.setText("NON VEG.");
        btnnonveg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnonvegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnnonveg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnveg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndessert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(btndessert)
                .addGap(18, 18, 18)
                .addComponent(btnveg)
                .addGap(18, 18, 18)
                .addComponent(btnnonveg)
                .addGap(26, 26, 26))
        );

        jLabel13.setFont(new java.awt.Font("AR BONNIE", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 51, 0));
        jLabel13.setText("Restaurant");

        jLabel15.setFont(new java.awt.Font("Megadeth", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 0));
        jLabel15.setText("NAME");

        jLabel16.setFont(new java.awt.Font("Megadeth", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 0));
        jLabel16.setText("BALANCE");

        jLabel18.setFont(new java.awt.Font("Megadeth", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 0));
        jLabel18.setText("MOBILE NO.");

        jLabel19.setFont(new java.awt.Font("Megadeth", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 0));
        jLabel19.setText("DESSERTS TOTAL");

        jLabel20.setFont(new java.awt.Font("Megadeth", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 0));
        jLabel20.setText("VEG. TOTAL");

        jLabel21.setFont(new java.awt.Font("Megadeth", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 0));
        jLabel21.setText("NON VEG. TOTAL");

        tfname.setEditable(false);
        tfname.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });

        tfbalance.setEditable(false);
        tfbalance.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N

        tfmobile.setEditable(false);
        tfmobile.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N

        tfdessert.setEditable(false);
        tfdessert.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N

        tfveg.setEditable(false);
        tfveg.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        tfveg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfvegActionPerformed(evt);
            }
        });

        tfnonveg.setEditable(false);
        tfnonveg.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Megadeth", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 0));
        jLabel23.setText("TOTAL PAYMENT");

        tftotalpayment.setEditable(false);
        tftotalpayment.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        tftotalpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftotalpaymentActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Megadeth", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 0));
        jLabel24.setText("NET BILL");

        tfdiscount.setEditable(false);
        tfdiscount.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        tfdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdiscountActionPerformed(evt);
            }
        });

        btndesserttotal.setText("D. TOTAL");
        btndesserttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndesserttotalActionPerformed(evt);
            }
        });

        btnvegtotal.setText("V. TOTAL");
        btnvegtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvegtotalActionPerformed(evt);
            }
        });

        btnnonvegtotal.setText("N. TOTAL");
        btnnonvegtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnonvegtotalActionPerformed(evt);
            }
        });

        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnbill.setText("CALCULATE BILL");
        btnbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillActionPerformed(evt);
            }
        });

        btnorder.setText("ORDER ");
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Megadeth", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 0));
        jLabel31.setText("DISCOUNT");

        tfnetbill.setEditable(false);
        tfnetbill.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N

        javax.swing.GroupLayout F4Layout = new javax.swing.GroupLayout(F4.getContentPane());
        F4.getContentPane().setLayout(F4Layout);
        F4Layout.setHorizontalGroup(
            F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(F4Layout.createSequentialGroup()
                .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(F4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, F4Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(154, 154, 154)
                                    .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfmobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                            .addComponent(tfbalance, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, F4Layout.createSequentialGroup()
                                    .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnorder, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel19)))
                                    .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(F4Layout.createSequentialGroup()
                                            .addGap(44, 44, 44)
                                            .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(F4Layout.createSequentialGroup()
                                                    .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(F4Layout.createSequentialGroup()
                                                            .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(tfveg, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(tfdessert, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(btndesserttotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnvegtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addGroup(F4Layout.createSequentialGroup()
                                                            .addComponent(tfnonveg, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(btnnonvegtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                    .addGap(68, 68, 68))
                                                .addGroup(F4Layout.createSequentialGroup()
                                                    .addComponent(btnbill, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(F4Layout.createSequentialGroup()
                                            .addGap(88, 88, 88)
                                            .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(81, 81, 81)
                                            .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, F4Layout.createSequentialGroup()
                                    .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel31)
                                        .addComponent(jLabel24))
                                    .addGap(44, 44, 44)
                                    .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tftotalpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfnetbill, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(F4Layout.createSequentialGroup()
                                .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(F4Layout.createSequentialGroup()
                                        .addGap(503, 503, 503)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(89, 89, 89))))
                    .addGroup(F4Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel13)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        F4Layout.setVerticalGroup(
            F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, F4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(F4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndesserttotal))
                        .addGap(18, 18, 18)
                        .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfveg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(btnvegtotal))
                        .addGap(18, 18, 18)
                        .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnonveg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(btnnonvegtotal))
                        .addGap(24, 24, 24)
                        .addComponent(btnbill))
                    .addGroup(F4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftotalpayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(11, 11, 11)
                .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfnetbill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnorder)
                    .addComponent(btnclear)
                    .addComponent(btnexit))
                .addGap(85, 85, 85))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panellogin2.setBackground(new java.awt.Color(204, 204, 204));
        panellogin2.setForeground(new java.awt.Color(0, 153, 204));

        lblusername2.setText("Username");

        lblpassword2.setText("Password");

        jLabel30.setText("Enter Username and Password To Continue");

        btnsubmit2.setText("Submit");
        btnsubmit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panellogin2Layout = new javax.swing.GroupLayout(panellogin2);
        panellogin2.setLayout(panellogin2Layout);
        panellogin2Layout.setHorizontalGroup(
            panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogin2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panellogin2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblusername2)
                    .addComponent(lblpassword2))
                .addGap(22, 22, 22)
                .addGroup(panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panellogin2Layout.createSequentialGroup()
                        .addComponent(tfusername2)
                        .addGap(22, 22, 22))
                    .addGroup(panellogin2Layout.createSequentialGroup()
                        .addGroup(panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfpassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panellogin2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnsubmit2)))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        panellogin2Layout.setVerticalGroup(
            panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogin2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addGroup(panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusername2)
                    .addComponent(tfusername2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassword2)
                    .addComponent(pfpassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsubmit2)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panellogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellogin2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        this.setVisible(false);
        Exit.setVisible(false);
        new Restaurant().setVisible(true);
               
    }//GEN-LAST:event_jButton15ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int a;
        DesL.setVisible(false);
        a = Integer.parseInt(a1.getText());
        tfdessert.setText(""+a);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int sum=0,b;
        String a;
        if(list1.isSelectedIndex(0)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Tarte Aux Pacanes");
            b = Integer.parseInt(a);
            sum = (sum + (195*b));
        }
        if(list1.isSelectedIndex(1)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Tarte à la Maringe au citron");
            b = Integer.parseInt(a);
            sum = (sum + (195*b));
        }
        if(list1.isSelectedIndex(2)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Pizza glacee et son coilis");
            b = Integer.parseInt(a);
            sum = (sum + (225*b));
        }
        if(list1.isSelectedIndex(3)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Creme glacee");
            b = Integer.parseInt(a);
            sum = (sum + (225*b));
        }
        if(list1.isSelectedIndex(4)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Extra Creme glacee");
            b = Integer.parseInt(a);
            sum = (sum + (75*b));
        }
        if(list1.isSelectedIndex(5)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Gateau aux carotte Elite");
            b = Integer.parseInt(a);
            sum = (sum + (225*b));
        }
        if(list1.isSelectedIndex(6)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Gateau aux carotte Elite");
            b = Integer.parseInt(a);
            sum = (sum + (225*b));
        }
        if(list1.isSelectedIndex(7)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Gateau au fudge chaud");
            b = Integer.parseInt(a);
            sum = (sum + (225*b));
        }
        if(list1.isSelectedIndex(8)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Gateau au chocol et framboises");
            b = Integer.parseInt(a);
            sum = (sum + (225*b));
        }
        if(list1.isSelectedIndex(9)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Tarte caramel et choclate malte");
            b = Integer.parseInt(a);
            sum = (sum + (225*b));
        }
        if(list1.isSelectedIndex(10)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Gateau formage aux pacanes t au caramel");
            b = Integer.parseInt(a);
            sum = (sum + (225*b));
        }
        if(list1.isSelectedIndex(11)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Tarte aux pommes epassie");
            b = Integer.parseInt(a);
            sum = (sum + (195*b));
        }
        if(list1.isSelectedIndex(12)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Tarte aux fruits de la foret");
            b = Integer.parseInt(a);
            sum = (sum + (195*b));
        }

        a1.setText(""+sum);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        int sum=0,b;
        String a;
        if(list2.isSelectedIndex(0)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Subz Handi");
            b = Integer.parseInt(a);
            sum = (sum + (110*b));
        }
        if(list2.isSelectedIndex(1)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Dum ki Gobi");
            b = Integer.parseInt(a);
            sum = (sum + (110*b));
        }
        if(list2.isSelectedIndex(2)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Corn Capsium");
            b = Integer.parseInt(a);
            sum = (sum + (110*b));
        }
        if(list2.isSelectedIndex(3)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Lucknowi Kofta");
            b = Integer.parseInt(a);
            sum = (sum + (125*b));
        }
        if(list2.isSelectedIndex(4)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Dingri mutter Harapyaz");
            b = Integer.parseInt(a);
            sum = (sum + (110*b));
        }
        if(list2.isSelectedIndex(5)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Vg makhan wala");
            b = Integer.parseInt(a);
            sum = (sum + (110*b));
        }
        if(list2.isSelectedIndex(6)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Channa masala");
            b = Integer.parseInt(a);
            sum = (sum + (110*b));
        }
        if(list2.isSelectedIndex(7)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Navarthna Korma");
            b = Integer.parseInt(a);
            sum = (sum + (110*b));
        }
        if(list2.isSelectedIndex(8)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Methi mutter wali");
            b = Integer.parseInt(a);
            sum = (sum + (110*b));
        }
        if(list2.isSelectedIndex(9)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Bhindi Masala");
            b = Integer.parseInt(a);
            sum = (sum + (110*b));
        }
        if(list2.isSelectedIndex(10)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Baigan bharta");
            b = Integer.parseInt(a);
            sum = (sum + (110*b));
        }
        if(list2.isSelectedIndex(11)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Dum aloo Kashmiri");
            b = Integer.parseInt(a);
            sum = (sum + (125*b));
        }
        if(list2.isSelectedIndex(12)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Stuffed capsicum Masala");
            b = Integer.parseInt(a);
            sum = (sum + (125*b));
        }

        a2.setText(""+sum);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        int a;
        vegL.setVisible(false);
        a = Integer.parseInt(a2.getText());
        tfveg.setText(""+a);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        int sum=0,b;
        String a;
        if(list3.isSelectedIndex(0)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Dhanya Murgh");
            b = Integer.parseInt(a);
            sum = (sum + (155*b));
        }
        if(list3.isSelectedIndex(1)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Muragh Peshawari");
            b = Integer.parseInt(a);
            sum = (sum + (165*b));
        }
        if(list3.isSelectedIndex(2)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Murh Handi");
            b = Integer.parseInt(a);
            sum = (sum + (155*b));
        }
        if(list3.isSelectedIndex(3)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Kadai Chicken");
            b = Integer.parseInt(a);
            sum = (sum + (155*b));
        }
        if(list3.isSelectedIndex(4)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Chicken Hydrabadi");
            b = Integer.parseInt(a);
            sum = (sum + (155*b));
        }
        if(list3.isSelectedIndex(5)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Chicken Mughlai");
            b = Integer.parseInt(a);
            sum = (sum + (155*b));
        }
        if(list3.isSelectedIndex(6)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Chicken Tikka Masala");
            b = Integer.parseInt(a);
            sum = (sum + (155*b));
        }
        if(list3.isSelectedIndex(7)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Chicken Butter Masala");
            b = Integer.parseInt(a);
            sum = (sum + (155*b));
        }
        if(list3.isSelectedIndex(8)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Chicken Dopiaza");
            b = Integer.parseInt(a);
            sum = (sum + (165*b));
        }
        if(list3.isSelectedIndex(9)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Murgh Patiyala");
            b = Integer.parseInt(a);
            sum = (sum + (165*b));
        }
        if(list3.isSelectedIndex(10)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Laal Maas");
            b = Integer.parseInt(a);
            sum = (sum + (185*b));
        }
        if(list3.isSelectedIndex(11)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Gosht Khada Masala");
            b = Integer.parseInt(a);
            sum = (sum + (185*b));
        }
        if(list3.isSelectedIndex(12)==true)
        {
            a = JOptionPane.showInputDialog("No. Of Order Of Dum ki Gosht ");
            b = Integer.parseInt(a);
            sum = (sum + (185*b));
        }
        a3.setText(""+sum);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        int a;
        nvegL.setVisible(false);
        a = Integer.parseInt(a3.getText());
        tfnonveg.setText(""+a);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void btndessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndessertActionPerformed
        Des.setVisible(true);
        Des.setSize(456,785);
    }//GEN-LAST:event_btndessertActionPerformed

    private void btnvegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvegActionPerformed
        veg.setVisible(true);
        veg.setSize(970,760);
    }//GEN-LAST:event_btnvegActionPerformed

    private void btnnonvegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnonvegActionPerformed
        nveg.setVisible(true);
        nveg.setSize(970,760);
    }//GEN-LAST:event_btnnonvegActionPerformed

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameActionPerformed

    private void tfvegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfvegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfvegActionPerformed

    private void tftotalpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftotalpaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftotalpaymentActionPerformed

    private void tfdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdiscountActionPerformed

    private void btndesserttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndesserttotalActionPerformed
        DesL.setVisible(true);
        DesL.setSize(784, 393);
    }//GEN-LAST:event_btndesserttotalActionPerformed

    private void btnvegtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvegtotalActionPerformed
        vegL.setVisible(true);
        vegL.setSize(784, 393);
    }//GEN-LAST:event_btnvegtotalActionPerformed

    private void btnnonvegtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnonvegtotalActionPerformed
        nvegL.setVisible(true);
        nvegL.setSize(784, 393);
    }//GEN-LAST:event_btnnonvegtotalActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        Exit.setVisible(true);
        Exit.setSize(1035, 736);
        F4.setVisible(false);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillActionPerformed
        double dessert,veg,nonveg,payment,bill;
        int discount;
        dessert = Double.parseDouble(tfdessert.getText());
        veg = Double.parseDouble(tfveg.getText());
        nonveg = Double.parseDouble(tfnonveg.getText());
        payment = dessert+veg+nonveg;
        tftotalpayment.setText(""+payment);
        if(payment>=1000)
        {
           discount=(int) (payment*0.02);
        }
       
        else if(payment>=2000)
        {
            discount=(int) (payment*0.05);
        }
        else if(payment>=5000)
        {
            discount=(int) (payment*0.1);
        }
        else if(payment>=10000)
        {
            discount=(int) (payment*0.15);
        }
        else
        {
            discount=0;
        }
        tfdiscount.setText(""+discount);
        bill=payment-discount;
        tfnetbill.setText(""+bill);
    }//GEN-LAST:event_btnbillActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://Localhost:3306/boomboom","root","12345");
            Statement stmt = con.createStatement();
            
          Double balance=Double.parseDouble(tfbalance.getText());  
          String  name = tfname.getText();
          String username = tfusername2.getText();
          Double dessert=Double.parseDouble(tfdessert.getText());
          Double veg=Double.parseDouble(tfveg.getText());
          Double nonveg=Double.parseDouble(tfnonveg.getText());
          Double bill = Double.parseDouble(tfnetbill.getText());    
          if(balance>bill)
          {
          stmt.executeUpdate("insert into restaurant values('"+(username)+"','"+(name)+"',"+(veg)+","+(nonveg)+","+(dessert)+","+(bill)+")");
          balance=balance-bill;
          tfbalance.setText(""+balance);
           String query3="Update Customer set Balance="+(balance)+" where username='"+(username)+"'";
            stmt.executeUpdate(query3);
            JOptionPane.showMessageDialog(null, "Your order have been placed succeesfully.");
          }
          else
          {
              JOptionPane.showMessageDialog(this,"You don't have enough balance to pay bill.");
          }
            tfdessert.setText("");
            tfveg.setText("");
            tfnonveg.setText("");
            tfnetbill.setText("");
            tftotalpayment.setText("");
            tfdiscount.setText("");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnorderActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        tfnetbill.setText("");
        tfdessert.setText("");
        tfnonveg.setText("");
        tfveg.setText("");       
        tftotalpayment.setText("");
        tfdiscount.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnsubmit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmit2ActionPerformed
        try
        {
           
            String username=tfusername2.getText();
            String password=pfpassword2.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            String query = "SELECT * FROM Customer  WHERE username = '" +(username) + "' and password='"+(password)+"'" ;
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
                String mobile=rs.getString("mobile");
                String name=rs.getString("name");
                String card=rs.getString("Card");
                Double balance = rs.getDouble("balance");
                if(card.equals("Gold"))
                {
                    JOptionPane.showMessageDialog(this,"You can't enter the Restaurant as your Credit Card is Gold type.");
                    this.setVisible(false);
                    new Restaurant().setVisible(true);
                }
                 else
                {
                this.setVisible(false);
                panellogin2.setVisible(false);
                F4.setVisible(true);
                F4.setSize(900,800);
                tfname.setText(""+name);
                tfbalance.setText(""+balance);
                tfmobile.setText(""+mobile);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Invalid Username or Password");
                tfusername2.setText("");
                pfpassword2.setText("");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"beda gark"+"\n"+e.getMessage());
        }
      

       
    }//GEN-LAST:event_btnsubmit2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Food().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Des;
    private javax.swing.JFrame DesL;
    private javax.swing.JFrame Exit;
    private javax.swing.JFrame F4;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JButton btnbill;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndessert;
    private javax.swing.JButton btndesserttotal;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnnonveg;
    private javax.swing.JButton btnnonvegtotal;
    private javax.swing.JButton btnorder;
    private javax.swing.JButton btnsubmit2;
    private javax.swing.JButton btnveg;
    private javax.swing.JButton btnvegtotal;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblpassword2;
    private javax.swing.JLabel lblusername2;
    private javax.swing.JList list1;
    private javax.swing.JList list2;
    private javax.swing.JList list3;
    private javax.swing.JFrame nveg;
    private javax.swing.JFrame nvegL;
    private javax.swing.JPanel panellogin2;
    private javax.swing.JPasswordField pfpassword2;
    private javax.swing.JTextField tfbalance;
    private javax.swing.JTextField tfdessert;
    private javax.swing.JTextField tfdiscount;
    private javax.swing.JTextField tfmobile;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfnetbill;
    private javax.swing.JTextField tfnonveg;
    private javax.swing.JTextField tftotalpayment;
    private javax.swing.JTextField tfusername2;
    private javax.swing.JTextField tfveg;
    private javax.swing.JFrame veg;
    private javax.swing.JFrame vegL;
    // End of variables declaration//GEN-END:variables
}
