
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Micronet
 */
public class Gamble extends javax.swing.JFrame {

    /**
     * Creates new form Gamble
     */
    public Gamble() {
        initComponents();
        this.setSize(900,700);
        paneloutput.setVisible(false);
        panelgamble.setVisible(false);
        lblbalance.setVisible(false);
        tfbalance.setVisible(false);
        lblroulette.setVisible(false);
        lbltable.setVisible(false);
         this.setIconImage(new ImageIcon(getClass().getResource("/Images/GamblersBarnstar-by-Everstar.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panellogin = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        pfpassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        lblroulette = new javax.swing.JLabel();
        lbltable = new javax.swing.JLabel();
        lblbalance = new javax.swing.JLabel();
        tfbalance = new javax.swing.JTextField();
        lblcasino = new javax.swing.JLabel();
        paneloutput = new javax.swing.JPanel();
        tfstatus = new javax.swing.JTextField();
        tfamount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfoutput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnplayagain = new javax.swing.JButton();
        btngoback = new javax.swing.JButton();
        panelgamble = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfmoney = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btngamble = new javax.swing.JButton();
        combogamble = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panellogin.setBackground(new java.awt.Color(204, 204, 204));
        panellogin.setForeground(new java.awt.Color(0, 153, 204));

        lblusername.setText("Username");

        jLabel8.setText("Password");

        jLabel9.setText("Enter Username and Password To Continue");

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelloginLayout = new javax.swing.GroupLayout(panellogin);
        panellogin.setLayout(panelloginLayout);
        panelloginLayout.setHorizontalGroup(
            panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelloginLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelloginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblusername)
                    .addComponent(jLabel8))
                .addGap(22, 22, 22)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelloginLayout.createSequentialGroup()
                        .addComponent(btnsubmit)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelloginLayout.createSequentialGroup()
                        .addComponent(pfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(panelloginLayout.createSequentialGroup()
                        .addComponent(tfusername)
                        .addGap(22, 22, 22))))
        );
        panelloginLayout.setVerticalGroup(
            panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelloginLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusername)
                    .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsubmit)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lblroulette.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GamblersBarnstar-by-Everstar.png"))); // NOI18N

        lbltable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/table.jpg"))); // NOI18N
        lbltable.setText("jLabel2");

        lblbalance.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblbalance.setText("Credit Card Balance");

        tfbalance.setEditable(false);
        tfbalance.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N

        lblcasino.setFont(new java.awt.Font("Vijaya", 3, 36)); // NOI18N
        lblcasino.setForeground(new java.awt.Color(0, 153, 204));
        lblcasino.setText("Casino");

        tfstatus.setEditable(false);
        tfstatus.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        tfstatus.setForeground(new java.awt.Color(204, 0, 51));

        tfamount.setEditable(false);
        tfamount.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        tfamount.setForeground(new java.awt.Color(0, 153, 255));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel5.setText("Status");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel6.setText("Amount");

        tfoutput.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel7.setText("Output");

        btnplayagain.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnplayagain.setText("Play Again");
        btnplayagain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplayagainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneloutputLayout = new javax.swing.GroupLayout(paneloutput);
        paneloutput.setLayout(paneloutputLayout);
        paneloutputLayout.setHorizontalGroup(
            paneloutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneloutputLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(paneloutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(62, 62, 62)
                .addGroup(paneloutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneloutputLayout.createSequentialGroup()
                        .addComponent(tfamount, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(paneloutputLayout.createSequentialGroup()
                        .addComponent(tfoutput, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneloutputLayout.createSequentialGroup()
                        .addComponent(tfstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(btnplayagain)
                        .addGap(32, 32, 32))))
        );
        paneloutputLayout.setVerticalGroup(
            paneloutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneloutputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneloutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfoutput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneloutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnplayagain))
                .addGap(18, 18, 18)
                .addGroup(paneloutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfamount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btngoback.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btngoback.setText("Go Back");
        btngoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngobackActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel4.setText("Gamble On");

        tfmoney.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel3.setText("Money To Gamble");

        btngamble.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btngamble.setText("Gamble");
        btngamble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngambleActionPerformed(evt);
            }
        });

        combogamble.setBackground(new java.awt.Color(0, 51, 51));
        combogamble.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        combogamble.setForeground(new java.awt.Color(0, 153, 0));
        combogamble.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1st 12", "2nd 12", "3rd 12", "1 to 18", "19 to 36", "Odd", "Even", "Red", "Black", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36" }));
        combogamble.setOpaque(false);

        javax.swing.GroupLayout panelgambleLayout = new javax.swing.GroupLayout(panelgamble);
        panelgamble.setLayout(panelgambleLayout);
        panelgambleLayout.setHorizontalGroup(
            panelgambleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelgambleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelgambleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panelgambleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combogamble, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btngamble)
                .addGap(44, 44, 44))
        );
        panelgambleLayout.setVerticalGroup(
            panelgambleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelgambleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelgambleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btngamble))
                .addGap(18, 18, 18)
                .addGroup(panelgambleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combogamble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btngoback)
                        .addGap(238, 238, 238)
                        .addComponent(lblcasino, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(tfbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(panellogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblroulette)
                        .addGap(42, 42, 42)
                        .addComponent(lbltable, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelgamble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paneloutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panellogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcasino)
                            .addComponent(btngoback))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbalance))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblroulette))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lbltable)))
                .addGap(24, 24, 24)
                .addComponent(panelgamble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneloutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngambleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngambleActionPerformed
              
        double balance=Double.parseDouble(tfbalance.getText());
        double money=Integer.parseInt(tfmoney.getText());
        if(balance>money)
        {
        panelgamble.setVisible(false);
        paneloutput.setVisible(true);
        int output=((int)(Math.random()*36));
        JOptionPane.showMessageDialog(this,output);
        tfoutput.setText(""+output);     
        double net,amount = 0;
        switch(combogamble.getSelectedIndex())
        {
            case 0: if(output>=1 && output<=12)
            {
                amount=money*3;                
            }
            else
            {
                amount=0;
            }
            break;
            case 1: if(output>=13 && output<=24)
            {
                amount=money*3;                
            }
            else
            {
                amount=0;
            }
            break;
            case 2: if(output>=25 && output<=36)
            {
                amount=money*3;                
            }
            else
            {
                amount=0;
            }
            break;
            case 3: if(output>=1 && output<=18)
            {
                amount=money*2;                
            }
            else
            {
                amount=0;
            }
            break;
            case 4: if(output>=19 && output<=36)
            {
                amount=money*2;                
            }
            else
            {
                amount=0;
            }
            break;   
            case 5: if(output%2==1)
            {
                amount=money*2;                
            }
            else
            {
                amount=0;
            }
            break;
            case 6: if(output%2==0)
            {
                amount=money*2;                
            }
            else
            {
                amount=0;
            }
            break;
            case 7: if(output==1||output==3||output==5||output==7||output==9||output==12||output==14||output==16||output==18||output==19||output==21||output==23||output==25||output==27||output==30||output==32||output==34||output==36)
            {
                amount=money*2;                
            }
            else
            {
                amount=0;
            }
            break;
            case 8: if(output==2||output==4||output==6||output==8||output==10||output==11||output==13||output==15||output==17||output==20||output==22||output==24||output==26||output==28||output==29||output==31||output==33||output==35)
            {
                amount=money*2;
            }
            else
            {
                amount=0;
            }
            break;
            case 9: if(output==0)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 10: if(output==1)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 11: if(output==2)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 12: if(output==3)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 13: if(output==4)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 14: if(output==5)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 15: if(output==6)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 16: if(output==7)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 17: if(output==8)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 18: if(output==9)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 19: if(output==10)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 20: if(output==11)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 21: if(output==12)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 22: if(output==13)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 23: if(output==14)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 24: if(output==15)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 25: if(output==16)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 26: if(output==17)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 27: if(output==18)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 28: if(output==19)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 29: if(output==20)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 30: if(output==21)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 31: if(output==22)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 32: if(output==23)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 33: if(output==24)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 34: if(output==25)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 35: if(output==26)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 36: if(output==27)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 37: if(output==28)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 38: if(output==29)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 39: if(output==30)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 40: if(output==31)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 41: if(output==32)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 42: if(output==33)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 43: if(output==34)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 44: if(output==35)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
            case 45: if(output==36)
            {
                amount=money*36;
            }
            else
            {
                amount=0;
            }
            break;
        }
        net=amount-money;
        if(net>0)
        {
            tfstatus.setText("Profit");
            tfamount.setText(""+net);
        }
        else if(net<0)
        {
            tfstatus.setText("Loss");
            tfamount.setText(""+money);
        }
        else
        {
            tfstatus.setText("No Profit,No Loss");
            tfamount.setText("0");
        }
        double total= (balance+net);
        tfbalance.setText(""+total);
        String status=tfstatus.getText();
      
        try
        {
         String username=tfusername.getText();
         String password=pfpassword.getText(); 
        Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            ResultSet rs=null;
            Statement stmt = con.createStatement();
             String query = "Update Customer Set balance="+(total)+" where username = '" +(username) + "' && password='"+(password)+"'" ;
            stmt.executeUpdate(query);
            String query1="Select * from customer where username='"+(username)+"'";
            rs=stmt.executeQuery(query1);
            if(rs.next())
            {  
            String name=rs.getString("Name");
            String query2="Insert into Casino values('"+(username)+"','"+(name)+"',"+(money)+",'"+(status)+"',"+(amount)+","+(net)+") "; 
            stmt.executeUpdate(query2);
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
       }
       else
       {
           JOptionPane.showMessageDialog(this,"The gambling money is more than your Credit Card balance"+"\n"+"You can sell some books at half price to earn money");
       }
      
    }//GEN-LAST:event_btngambleActionPerformed

    private void btnplayagainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplayagainActionPerformed
        panelgamble.setVisible(true);
        paneloutput.setVisible(false);
        tfoutput.setText("");
        tfstatus.setText("");
        tfamount.setText("");
    }//GEN-LAST:event_btnplayagainActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
            try
        {
            String username=tfusername.getText();
            String password=pfpassword.getText();  
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            String query = "SELECT * FROM Customer  WHERE username = '" +(username) + "' && password='"+(password)+"'" ;
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

           if(rs.next())
           {          
                String card=rs.getString("card");
                Double balance = rs.getDouble("balance");
              
                if(card.equals("Platinum"))
                {
                    JOptionPane.showMessageDialog(this,"Your Credit Card is Platinum type"+"\n"+"So,you can't enter the Casino");
                    this.setVisible(false);
                    new Casino().setVisible(true);
                }
                 else
                {
                tfbalance.setText(""+balance);
                panelgamble.setVisible(true);
                lblbalance.setVisible(true);
                tfbalance.setVisible(true);
              lblroulette.setVisible(true);
              lbltable.setVisible(true);
              panellogin.setVisible(false);
                }
            
           }
            else
            {
                JOptionPane.showMessageDialog(this,"Invalid Username or Password");
                tfusername.setText("");
                    pfpassword.setText("");
            }
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this,e.getMessage());
                }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btngobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngobackActionPerformed
        this.setVisible(false);
        new Casino().setVisible(true);
    }//GEN-LAST:event_btngobackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gamble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gamble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gamble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gamble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gamble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngamble;
    private javax.swing.JButton btngoback;
    private javax.swing.JButton btnplayagain;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox combogamble;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblbalance;
    private javax.swing.JLabel lblcasino;
    private javax.swing.JLabel lblroulette;
    private javax.swing.JLabel lbltable;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPanel panelgamble;
    private javax.swing.JPanel panellogin;
    private javax.swing.JPanel paneloutput;
    private javax.swing.JPasswordField pfpassword;
    private javax.swing.JTextField tfamount;
    private javax.swing.JTextField tfbalance;
    private javax.swing.JTextField tfmoney;
    private javax.swing.JTextField tfoutput;
    private javax.swing.JTextField tfstatus;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
