
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Micronet
 */
public class NewCustomerLetter extends javax.swing.JFrame {

    /**
     * Creates new form NewCustomerLetter
     */
    public NewCustomerLetter() {
        initComponents();
        lblletter.setVisible(false);
        btncheckoutmall.setVisible(false);
        btnexit.setVisible(false);
         this.setIconImage(new ImageIcon(getClass().getResource("/Images/close letter.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcloseletter = new javax.swing.JLabel();
        btnopenletter = new javax.swing.JButton();
        lblletter = new javax.swing.JLabel();
        btncheckoutmall = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblcloseletter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close letter.jpg"))); // NOI18N

        btnopenletter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnopenletter.setText("Open Letter");
        btnopenletter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenletterActionPerformed(evt);
            }
        });

        lblletter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Text Letter.jpg"))); // NOI18N

        btncheckoutmall.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncheckoutmall.setText("Enroll");
        btncheckoutmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckoutmallActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnexit.setText("No Thanks");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblcloseletter)
                        .addGap(71, 71, 71)
                        .addComponent(btnopenletter))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblletter)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnexit)
                            .addComponent(btncheckoutmall, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(btncheckoutmall)
                .addGap(69, 69, 69)
                .addComponent(btnexit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnopenletter))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblcloseletter, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblletter, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void btncheckoutmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckoutmallActionPerformed
          new CustomerDetails().setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_btncheckoutmallActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnopenletterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenletterActionPerformed
       lblcloseletter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/open letter.jpg")));
       lblletter.setVisible(true);
       btncheckoutmall.setVisible(true);
       btnexit.setVisible(true);
       btnopenletter.setVisible(false);
    }//GEN-LAST:event_btnopenletterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCustomerLetter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCustomerLetter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCustomerLetter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCustomerLetter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCustomerLetter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckoutmall;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnopenletter;
    private javax.swing.JLabel lblcloseletter;
    private javax.swing.JLabel lblletter;
    // End of variables declaration//GEN-END:variables
}
