
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Micronet
 */
public class Parking extends javax.swing.JFrame {

    /**
     * Creates new form Parking
     */
    public Parking() {
        initComponents();
        panellift.setVisible(false);
        panelparking.setVisible(false);
         this.setIconImage(new ImageIcon(getClass().getResource("/Images/Parking.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        btnparking = new javax.swing.JButton();
        btnlift = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panellift = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        combolift = new javax.swing.JComboBox();
        btnliftgo = new javax.swing.JButton();
        btnliftcancel = new javax.swing.JButton();
        panelparking = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnparkingyes = new javax.swing.JButton();
        btnparkingno = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnparking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Parking.jpg"))); // NOI18N
        btnparking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparkingActionPerformed(evt);
            }
        });

        btnlift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/elevator.jpg"))); // NOI18N
        btnlift.setText("jButton1");
        btnlift.setOpaque(false);
        btnlift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnliftActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setText("Ground Floor : PARKING LOT");

        panellift.setBackground(new java.awt.Color(204, 204, 204));
        panellift.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setText("Go To ");

        combolift.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combolift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ground    :   Parking Lot", "I Floor     :   Books Shop", "II Floor    :   Restaurant", "III Floor   :   Cinema Hall", "IV Floor    :   Casino" }));

        btnliftgo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnliftgo.setText("Go To Floor");
        btnliftgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnliftgoActionPerformed(evt);
            }
        });

        btnliftcancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnliftcancel.setText("Cancel");
        btnliftcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnliftcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelliftLayout = new javax.swing.GroupLayout(panellift);
        panellift.setLayout(panelliftLayout);
        panelliftLayout.setHorizontalGroup(
            panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelliftLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelliftLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combolift, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelliftLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnliftgo)
                        .addGap(32, 32, 32)
                        .addComponent(btnliftcancel)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelliftLayout.setVerticalGroup(
            panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelliftLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combolift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panelliftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnliftgo)
                    .addComponent(btnliftcancel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelparking.setBackground(new java.awt.Color(102, 102, 102));
        panelparking.setForeground(new java.awt.Color(0, 102, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Do you want to go home?");

        btnparkingyes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnparkingyes.setText("YES");
        btnparkingyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparkingyesActionPerformed(evt);
            }
        });

        btnparkingno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnparkingno.setText("NO");
        btnparkingno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparkingnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelparkingLayout = new javax.swing.GroupLayout(panelparking);
        panelparking.setLayout(panelparkingLayout);
        panelparkingLayout.setHorizontalGroup(
            panelparkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelparkingLayout.createSequentialGroup()
                .addGroup(panelparkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelparkingLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel3))
                    .addGroup(panelparkingLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnparkingyes)
                        .addGap(43, 43, 43)
                        .addComponent(btnparkingno)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        panelparkingLayout.setVerticalGroup(
            panelparkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelparkingLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelparkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnparkingyes)
                    .addComponent(btnparkingno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnparking, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnlift, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(panelparking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panellift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnparking, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlift, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panellift, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelparking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnparkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparkingActionPerformed
        panelparking.setVisible(true);
    }//GEN-LAST:event_btnparkingActionPerformed

    private void btnparkingnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparkingnoActionPerformed
         panelparking.setVisible(false);
    }//GEN-LAST:event_btnparkingnoActionPerformed

    private void btnliftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnliftActionPerformed
        panellift.setVisible(true);
    }//GEN-LAST:event_btnliftActionPerformed

    private void btnliftgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnliftgoActionPerformed
       switch(combolift.getSelectedIndex())
       {
           case 0: this.setVisible(false);
                new Parking().setVisible(true);
                 break;
           case 1: this.setVisible(false);
                new Books_Shop().setVisible(true);
                 break;
           case 2: this.setVisible(false);
                new Restaurant().setVisible(true);
                 break;
           case 3: this.setVisible(false);
                new Cinema_Hall().setVisible(true);
                 break;
           case 4: this.setVisible(false);
                new Casino().setVisible(true);
                 break;
         
       }        
    }//GEN-LAST:event_btnliftgoActionPerformed

    private void btnliftcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnliftcancelActionPerformed
        panellift.setVisible(false);
    }//GEN-LAST:event_btnliftcancelActionPerformed

    private void btnparkingyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparkingyesActionPerformed
               JOptionPane.showMessageDialog(this,"Thank You for coming to Boom Boom Mall"+"\n"+"Come back Soon,We are waiting for you...");
               new Start().setVisible(true);
               this.setVisible(false);
    }//GEN-LAST:event_btnparkingyesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlift;
    private javax.swing.JButton btnliftcancel;
    private javax.swing.JButton btnliftgo;
    private javax.swing.JButton btnparking;
    private javax.swing.JButton btnparkingno;
    private javax.swing.JButton btnparkingyes;
    private javax.swing.JComboBox combolift;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panellift;
    private javax.swing.JPanel panelparking;
    // End of variables declaration//GEN-END:variables
}
