import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Micronet
 */
public class Products_Department extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Department
     */
    public Products_Department() {
        initComponents();    
        panelnewbook.setVisible(false);
        paneldeletebook.setVisible(false);
        panelnewmovie.setVisible(false);
        paneldeletemovie.setVisible(false);
        panelprice.setVisible(false);
       
       this.setIconImage(new ImageIcon(getClass().getResource("/Manager/boomboom23.jpg")).getImage());
        combobooktype.setVisible(false);
        combomovietype.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        paneldeletebook = new javax.swing.JScrollPane();
        IFdeletebook = new javax.swing.JInternalFrame();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        combosearchcriteria = new javax.swing.JComboBox();
        tfsearch = new javax.swing.JTextField();
        combobooktype = new javax.swing.JComboBox();
        btnsearchbook = new javax.swing.JButton();
        panelprice = new javax.swing.JPanel();
        tfminprice = new javax.swing.JTextField();
        tfmaxprice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbooksearch = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        tfdeletebookid = new javax.swing.JTextField();
        btndeletebook = new javax.swing.JButton();
        btnclearbook = new javax.swing.JButton();
        panelnewbook = new javax.swing.JScrollPane();
        IFnewbook = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfnewbookid = new javax.swing.JTextField();
        tfnewbooktitle = new javax.swing.JTextField();
        tfnewbookauthor = new javax.swing.JTextField();
        tfnewbookprice = new javax.swing.JTextField();
        btnnewbooksave = new javax.swing.JButton();
        btnnewbookclear = new javax.swing.JButton();
        combonewbooktype = new javax.swing.JComboBox();
        panelnewmovie = new javax.swing.JScrollPane();
        IFnewmovie = new javax.swing.JInternalFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tfnewmovieid = new javax.swing.JTextField();
        tfnewmovietitle = new javax.swing.JTextField();
        tfnewmovielead = new javax.swing.JTextField();
        btnnewmoviesave = new javax.swing.JButton();
        btnnewmovieclear = new javax.swing.JButton();
        combonewmovietype = new javax.swing.JComboBox();
        paneldeletemovie = new javax.swing.JScrollPane();
        IFdeletemovie = new javax.swing.JInternalFrame();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        combosearchcriteria1 = new javax.swing.JComboBox();
        tfsearch1 = new javax.swing.JTextField();
        combomovietype = new javax.swing.JComboBox();
        btnsearchmovie = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblmoviesearch = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        tfdeletemovieid = new javax.swing.JTextField();
        btndeletemovie = new javax.swing.JButton();
        btnclearmovie = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menubook = new javax.swing.JMenu();
        menunewbook = new javax.swing.JMenuItem();
        menudeletebook = new javax.swing.JMenuItem();
        menumovie = new javax.swing.JMenu();
        menunewmovie = new javax.swing.JMenuItem();
        menudeletemovie = new javax.swing.JMenuItem();
        menuexit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("PRODUCTS DEPARTMENT");

        IFdeletebook.setVisible(true);

        jLabel12.setFont(new java.awt.Font("Vijaya", 1, 18)); // NOI18N
        jLabel12.setText("Search Book");

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel13.setText("Search Criteria");

        combosearchcriteria.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        combosearchcriteria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Search by Book Title", "Search by Author Name", "Search by Book Type", "Search by Book Price" }));
        combosearchcriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosearchcriteriaActionPerformed(evt);
            }
        });

        tfsearch.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N

        combobooktype.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        combobooktype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biography", "Chemistry", "Comics", "Computer", "Love", "Novel", "Physics", "Religious", "Series" }));

        btnsearchbook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsearchbook.setText("Search");
        btnsearchbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchbookActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel14.setText("Maximum Price");

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel15.setText("Minimum Price");

        javax.swing.GroupLayout panelpriceLayout = new javax.swing.GroupLayout(panelprice);
        panelprice.setLayout(panelpriceLayout);
        panelpriceLayout.setHorizontalGroup(
            panelpriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpriceLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(37, 37, 37))
            .addGroup(panelpriceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfminprice, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(tfmaxprice, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelpriceLayout.setVerticalGroup(
            panelpriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpriceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelpriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfminprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfmaxprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblbooksearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"BOOK_ID", "BOOK_TITLE", "AUTHOR", "BOOK_TYPE", "PRICE"},
                {null, null, null, null, null}
            },
            new String [] {
                "Book_ID", "Book_Title", "Author", "Book_Type", "Price"
            }
        ));
        tblbooksearch.setDragEnabled(true);

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel16.setText("Enter Book_ID to Delete Book Record");

        tfdeletebookid.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        btndeletebook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndeletebook.setText("Delete Book Record");
        btndeletebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletebookActionPerformed(evt);
            }
        });

        btnclearbook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnclearbook.setText("Clear");
        btnclearbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearbookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IFdeletebookLayout = new javax.swing.GroupLayout(IFdeletebook.getContentPane());
        IFdeletebook.getContentPane().setLayout(IFdeletebookLayout);
        IFdeletebookLayout.setHorizontalGroup(
            IFdeletebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFdeletebookLayout.createSequentialGroup()
                .addGroup(IFdeletebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFdeletebookLayout.createSequentialGroup()
                        .addGroup(IFdeletebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IFdeletebookLayout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IFdeletebookLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(combobooktype, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))
                        .addComponent(panelprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFdeletebookLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFdeletebookLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combosearchcriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnsearchbook)
                        .addGap(36, 36, 36)
                        .addComponent(btnclearbook))
                    .addGroup(IFdeletebookLayout.createSequentialGroup()
                        .addGap(851, 851, 851)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFdeletebookLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(tblbooksearch, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFdeletebookLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFdeletebookLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfdeletebookid, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btndeletebook)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        IFdeletebookLayout.setVerticalGroup(
            IFdeletebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFdeletebookLayout.createSequentialGroup()
                .addGroup(IFdeletebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(IFdeletebookLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(19, 19, 19)
                        .addComponent(btnsearchbook))
                    .addGroup(IFdeletebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combosearchcriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(btnclearbook))
                .addGroup(IFdeletebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFdeletebookLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobooktype, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFdeletebookLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(tblbooksearch, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(IFdeletebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfdeletebookid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndeletebook))
                .addGap(21, 21, 21))
        );

        paneldeletebook.setViewportView(IFdeletebook);

        IFnewbook.setVisible(true);

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel2.setText("NEW BOOK");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Enter Book_ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setText("Enter Book_Title");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setText("Author Name");

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel10.setText("Book_Type");

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel11.setText("Book_Price");

        tfnewbookid.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        tfnewbooktitle.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        tfnewbookauthor.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        tfnewbookprice.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        btnnewbooksave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnnewbooksave.setText("Save Book Record");
        btnnewbooksave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewbooksaveActionPerformed(evt);
            }
        });

        btnnewbookclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnnewbookclear.setText("Clear");
        btnnewbookclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewbookclearActionPerformed(evt);
            }
        });

        combonewbooktype.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        combonewbooktype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biography", "Chemistry", "Comics", "Computer", "Love", "Novel", "Physics", "Religious", "Series" }));

        javax.swing.GroupLayout IFnewbookLayout = new javax.swing.GroupLayout(IFnewbook.getContentPane());
        IFnewbook.getContentPane().setLayout(IFnewbookLayout);
        IFnewbookLayout.setHorizontalGroup(
            IFnewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFnewbookLayout.createSequentialGroup()
                .addGroup(IFnewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFnewbookLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel2))
                    .addGroup(IFnewbookLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(IFnewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(IFnewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(IFnewbookLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnnewbooksave)
                                .addGap(76, 76, 76)
                                .addComponent(btnnewbookclear))
                            .addComponent(tfnewbookid)
                            .addComponent(tfnewbooktitle)
                            .addComponent(tfnewbookauthor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfnewbookprice)
                            .addComponent(combonewbooktype, 0, 402, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IFnewbookLayout.setVerticalGroup(
            IFnewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFnewbookLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addGroup(IFnewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfnewbookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(IFnewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfnewbooktitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(IFnewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfnewbookauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(IFnewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combonewbooktype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(IFnewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfnewbookprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(IFnewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnewbooksave)
                    .addComponent(btnnewbookclear)))
        );

        panelnewbook.setViewportView(IFnewbook);

        IFnewmovie.setVisible(true);

        jLabel17.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel17.setText("NEW MOVIE");

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel18.setText("Enter Movie_ID");

        jLabel19.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel19.setText("Enter Movie_Title");

        jLabel21.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel21.setText("Book_Type");

        jLabel22.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel22.setText("Lead Role");

        tfnewmovieid.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        tfnewmovietitle.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        tfnewmovielead.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        btnnewmoviesave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnnewmoviesave.setText("Save Movie Record");
        btnnewmoviesave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewmoviesaveActionPerformed(evt);
            }
        });

        btnnewmovieclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnnewmovieclear.setText("Clear");
        btnnewmovieclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewmovieclearActionPerformed(evt);
            }
        });

        combonewmovietype.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        combonewmovietype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Action", "Animation", "Comedy", "Drama", "Entertainment", "Hollywood", "Horror", "Romance", "Sports" }));

        javax.swing.GroupLayout IFnewmovieLayout = new javax.swing.GroupLayout(IFnewmovie.getContentPane());
        IFnewmovie.getContentPane().setLayout(IFnewmovieLayout);
        IFnewmovieLayout.setHorizontalGroup(
            IFnewmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFnewmovieLayout.createSequentialGroup()
                .addGroup(IFnewmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFnewmovieLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel17))
                    .addGroup(IFnewmovieLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(IFnewmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(IFnewmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(IFnewmovieLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnnewmoviesave)
                                .addGap(76, 76, 76)
                                .addComponent(btnnewmovieclear))
                            .addComponent(tfnewmovieid)
                            .addComponent(tfnewmovietitle)
                            .addComponent(tfnewmovielead)
                            .addComponent(combonewmovietype, 0, 402, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IFnewmovieLayout.setVerticalGroup(
            IFnewmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFnewmovieLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(49, 49, 49)
                .addGroup(IFnewmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfnewmovieid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(IFnewmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfnewmovietitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(IFnewmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combonewmovietype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(IFnewmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfnewmovielead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(IFnewmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnewmoviesave)
                    .addComponent(btnnewmovieclear)))
        );

        panelnewmovie.setViewportView(IFnewmovie);

        IFdeletemovie.setVisible(true);

        jLabel20.setFont(new java.awt.Font("Vijaya", 1, 18)); // NOI18N
        jLabel20.setText("Search Book");

        jLabel23.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel23.setText("Search Criteria");

        combosearchcriteria1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        combosearchcriteria1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Search by Movie Title", "Search by Lead Role", "Search by Movie Type" }));
        combosearchcriteria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosearchcriteria1ActionPerformed(evt);
            }
        });

        tfsearch1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N

        combomovietype.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        combomovietype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Action", "Animation", "Comedy", "Drama", "Entertainment", "Hollywood", "Horror", "Romance", "Sports" }));

        btnsearchmovie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsearchmovie.setText("Search");
        btnsearchmovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchmovieActionPerformed(evt);
            }
        });

        tblmoviesearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"MOVIE_ID", "MOVIE_TITLE", "MOVIE_TYPE", "LEAD_ROLE"},
                {null, null, null, null}
            },
            new String [] {
                "MOVIE_ID", "MOVIE_TITLE", "MOVIE_TYPE", "LEAD_ROLE"
            }
        ));
        tblmoviesearch.setDragEnabled(true);

        jLabel24.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel24.setText("Enter Movie_ID");

        tfdeletemovieid.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        btndeletemovie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndeletemovie.setText("Delete Movie Record");
        btndeletemovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletemovieActionPerformed(evt);
            }
        });

        btnclearmovie.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnclearmovie.setText("Clear");
        btnclearmovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearmovieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IFdeletemovieLayout = new javax.swing.GroupLayout(IFdeletemovie.getContentPane());
        IFdeletemovie.getContentPane().setLayout(IFdeletemovieLayout);
        IFdeletemovieLayout.setHorizontalGroup(
            IFdeletemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFdeletemovieLayout.createSequentialGroup()
                .addGroup(IFdeletemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFdeletemovieLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFdeletemovieLayout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFdeletemovieLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tblmoviesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFdeletemovieLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFdeletemovieLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfdeletemovieid, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(btndeletemovie))
                    .addGroup(IFdeletemovieLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(IFdeletemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IFdeletemovieLayout.createSequentialGroup()
                                .addComponent(combomovietype, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(tfsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(IFdeletemovieLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(combosearchcriteria1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(btnsearchmovie)
                                .addGap(29, 29, 29)
                                .addComponent(btnclearmovie)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IFdeletemovieLayout.setVerticalGroup(
            IFdeletemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFdeletemovieLayout.createSequentialGroup()
                .addGroup(IFdeletemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(IFdeletemovieLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(19, 19, 19)
                        .addGroup(IFdeletemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsearchmovie)
                            .addComponent(btnclearmovie)))
                    .addGroup(IFdeletemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combosearchcriteria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)))
                .addGap(19, 19, 19)
                .addGroup(IFdeletemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combomovietype, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(IFdeletemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tblmoviesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IFdeletemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdeletemovieid)
                    .addComponent(jLabel24)
                    .addComponent(btndeletemovie))
                .addGap(23, 23, 23))
        );

        paneldeletemovie.setViewportView(IFdeletemovie);

        menubook.setText("Books");

        menunewbook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menunewbook.setText("New Book");
        menunewbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunewbookActionPerformed(evt);
            }
        });
        menubook.add(menunewbook);

        menudeletebook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menudeletebook.setText("Delete Book");
        menudeletebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menudeletebookActionPerformed(evt);
            }
        });
        menubook.add(menudeletebook);

        jMenuBar1.add(menubook);

        menumovie.setText("Movies");

        menunewmovie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menunewmovie.setText("New Movie");
        menunewmovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunewmovieActionPerformed(evt);
            }
        });
        menumovie.add(menunewmovie);

        menudeletemovie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menudeletemovie.setText("Delete Movie");
        menudeletemovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menudeletemovieActionPerformed(evt);
            }
        });
        menumovie.add(menudeletemovie);

        jMenuBar1.add(menumovie);

        menuexit.setText("Exit");

        jMenuItem1.setText("Go to Manager's Department (Kuldeep)");
        jMenuItem1.setActionCommand("Go to Manager's Department (Kuldeep)");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuexit.add(jMenuItem1);

        jMenuBar1.add(menuexit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelnewmovie, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paneldeletemovie, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelnewbook, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(paneldeletebook, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(221, 221, 221)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(456, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelnewbook, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paneldeletebook, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelnewmovie, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneldeletemovie, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(649, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menunewbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunewbookActionPerformed
        panelnewbook.setVisible(true);
        panelnewbook.setBounds(10, 50, 900,600);
        IFnewbook.setBounds(10, 50, 900,600);
        paneldeletebook.setVisible(false);
        panelnewmovie.setVisible(false);
        paneldeletemovie.setVisible(false);
    }//GEN-LAST:event_menunewbookActionPerformed

    private void btnnewbookclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewbookclearActionPerformed
        tfnewbookid.setText("");
        tfnewbooktitle.setText("");
        tfnewbookauthor.setText("");
        tfnewbookprice.setText("");
    }//GEN-LAST:event_btnnewbookclearActionPerformed

    private void btnnewbooksaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewbooksaveActionPerformed
         String bookid=tfnewbookid.getText();
         String booktitle=tfnewbooktitle.getText();
         String author=tfnewbookauthor.getText();
         String booktype=(String) combonewbooktype.getSelectedItem();
         Double price=Double.parseDouble(tfnewbookprice.getText());
        try
        {
       
         Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            ResultSet rs=null;
            Statement stmt = con.createStatement();
            
         
           
            String query="insert into book(bookidd,Book_Title,Author,Book_Type,rate) values('"+(bookid)+"','"+(booktitle)+"','"+(author)+"','"+(booktype)+"',"+(price)+") "; 
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this,"The Book record has been succeesfully saved.");
          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"The Book record can't be saved."+"\n"+e.getMessage());
            
        }
            tfnewbookid.setText("");
            tfnewbooktitle.setText("");
            tfnewbookauthor.setText("");          
            tfnewbookprice.setText("");
    }//GEN-LAST:event_btnnewbooksaveActionPerformed

    private void combosearchcriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosearchcriteriaActionPerformed
        switch(combosearchcriteria.getSelectedIndex())
        {
            case 0: tfsearch.setVisible(true);
            combobooktype.setVisible(false);

            panelprice.setVisible(false);
            break;
            case 1: 
             tfsearch.setVisible(true);
            combobooktype.setVisible(false);

            panelprice.setVisible(false);
            break;
            case 2: tfsearch.setVisible(false);
            combobooktype.setVisible(true);

            panelprice.setVisible(false);
            break;
            case 3: tfsearch.setVisible(false);
            combobooktype.setVisible(false);

            panelprice.setVisible(true);
            break;

        }
    }//GEN-LAST:event_combosearchcriteriaActionPerformed

    private void btnsearchbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchbookActionPerformed
        DefaultTableModel model=(DefaultTableModel)tblbooksearch.getModel();
        int rows=model.getRowCount();
        if(rows>2)
        {
            for(int i=2;i<rows;i++)
            {
                model.removeRow(2);
            }
        }
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            ResultSet rs = null;
            Statement stmt = null;
            String query;
            String booksearch=tfsearch.getText();
            switch(combosearchcriteria.getSelectedIndex())
            {
                case 0:
                query = "SELECT * FROM book where Book_Title='"+(booksearch)+"'";
                stmt = con.createStatement();
                rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    model.addRow(new Object[]
                        {
                            rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getDouble(5)});
                }
                System.out.println(rs.getString(1));

                break;
                case 1:

                query = "SELECT * FROM book where Author='"+(booksearch)+"'";
                stmt = con.createStatement();
                rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    model.addRow(new Object[]
                        {
                            rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getDouble(5)});
                }

                break;
                case 2:
                String booktype=(String) combobooktype.getSelectedItem();

                query = "SELECT * FROM book where Book_Type='"+(booktype)+"'";
                stmt = con.createStatement();
                rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    model.addRow(new Object[]
                        {
                            rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getDouble(5)});
                }

                break;
                case 3:
                double minprice=Double.parseDouble(tfminprice.getText());
                double maxprice=Double.parseDouble(tfmaxprice.getText());
                query = "SELECT * FROM book where Price between'"+(minprice)+"'and'"+(maxprice)+"'";
                stmt = con.createStatement();
                rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    model.addRow(new Object[]
                        {
                            rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getDouble(5)});
                }

                break;

            }
            rs.close();
            stmt.close();
            con.close();
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_btnsearchbookActionPerformed

    private void menudeletebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menudeletebookActionPerformed
        paneldeletebook.setVisible(true);
        paneldeletebook.setBounds(10, 50, 900,600);
        IFdeletebook.setBounds(10, 50, 900,600);
        panelnewbook.setVisible(false);
        panelnewmovie.setVisible(false);
        paneldeletemovie.setVisible(false);
    }//GEN-LAST:event_menudeletebookActionPerformed

    private void btnnewmoviesaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewmoviesaveActionPerformed
        String movieid=tfnewmovieid.getText();
         String movietitle=tfnewmovietitle.getText();
         
         String movietype=(String) combonewmovietype.getSelectedItem();
         String leadrole=tfnewmovielead.getText();
        try
        {
       
         Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            ResultSet rs=null;
            Statement stmt = con.createStatement();
            
         
           
            String query="Insert into movie values('"+(movieid)+"','"+(movietitle)+"','"+(movietype)+"','"+(leadrole)+"') "; 
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this,"The Movie record has been succeesfully saved.");
          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"The Movie record can't be saved."+"\n"+e.getMessage());
            
        }
            tfnewmovieid.setText("");
            tfnewmovietitle.setText("");
            tfnewmovielead.setText("");
    }//GEN-LAST:event_btnnewmoviesaveActionPerformed

    private void btnnewmovieclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewmovieclearActionPerformed
        tfnewmovieid.setText("");
        tfnewmovietitle.setText("");
        tfnewmovielead.setText("");
        
    }//GEN-LAST:event_btnnewmovieclearActionPerformed

    private void combosearchcriteria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosearchcriteria1ActionPerformed
        switch(combosearchcriteria.getSelectedIndex())
        {
            case 0:
                tfsearch.setVisible(true);
            combomovietype.setVisible(false);

            break;
            case 1:
                tfsearch.setVisible(true);
            combomovietype.setVisible(false);

            break;
            case 2:
                tfsearch.setVisible(false);
            combomovietype.setVisible(true);

            break;

        }
    }//GEN-LAST:event_combosearchcriteria1ActionPerformed

    private void btnsearchmovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchmovieActionPerformed
        DefaultTableModel model=(DefaultTableModel)tblmoviesearch.getModel();
        int rows=model.getRowCount();
        if(rows>2)
        {
            for(int i=2;i<rows;i++)
            {
                model.removeRow(2);
            }
        }
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            ResultSet rs = null;
            Statement stmt = con.createStatement();
            String query;
            String moviesearch=tfsearch.getText();
            switch(combosearchcriteria.getSelectedIndex())
            {
                case 0:
                query = "SELECT * FROM movie where Movie_Title='"+(moviesearch)+"'";
               
                rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    model.addRow(new Object[]
                        {
                            rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
                }
              
                break;
                case 1:

                query = "SELECT * FROM movie where LeadRole='"+(moviesearch)+"'";
               
                rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    model.addRow(new Object[]
                        {
                            rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
                }

                break;
                case 2:
                String movietype=(String) combomovietype.getSelectedItem();

                query = "SELECT * FROM movie where movie_Type='"+(movietype)+"'";
              
                rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    model.addRow(new Object[]
                        {
                            rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
                }

                break;

            }
         
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btnsearchmovieActionPerformed

    private void btndeletemovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletemovieActionPerformed
        String movieid=tfdeletemovieid.getText();  
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            ResultSet rs = null;
            Statement stmt = con.createStatement();
           
            String query="Delete from movie where movie_id='"+(movieid)+"'";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this,"Movie record deleted succeesfully.");
        }
             catch(Exception e)
             {
                 JOptionPane.showMessageDialog(this,"Movie record can't be deleted"+"\n"+e.getMessage());
             }
    }//GEN-LAST:event_btndeletemovieActionPerformed

    private void btndeletebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletebookActionPerformed
           String bookid=tfdeletebookid.getText();  
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/boomboom","root","12345");
            ResultSet rs = null;
            Statement stmt = con.createStatement();
           
            String query="Delete from book where book_id='"+(bookid)+"'";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this,"Book record deleted succeesfully.");
        }
             catch(Exception e)
             {
                 JOptionPane.showMessageDialog(this,"Book record can't be deleted"+"\n"+e.getMessage());
             }
    }//GEN-LAST:event_btndeletebookActionPerformed

    private void menunewmovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunewmovieActionPerformed
        panelnewmovie.setVisible(true);
        panelnewmovie.setBounds(10, 50, 900,600);
        IFnewmovie.setBounds(10, 50, 800,600);
        paneldeletebook.setVisible(false);
        panelnewbook.setVisible(false);
        paneldeletemovie.setVisible(false);        
    }//GEN-LAST:event_menunewmovieActionPerformed

    private void menudeletemovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menudeletemovieActionPerformed
        paneldeletemovie.setVisible(true);
        paneldeletemovie.setBounds(10, 50, 900,600);
        IFdeletemovie.setBounds(10, 50, 900,600);
        paneldeletebook.setVisible(false);
        panelnewbook.setVisible(false);
        panelnewmovie.setVisible(false);      
    }//GEN-LAST:event_menudeletemovieActionPerformed

    private void btnclearbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearbookActionPerformed
        DefaultTableModel model=(DefaultTableModel)tblbooksearch.getModel();
        int rows=model.getRowCount();
        if(rows>2)
        {
            for(int i=2;i<rows;i++)
            {
                model.removeRow(2);
            }
        }
        
        tfsearch.setVisible(false);
        combobooktype.setVisible(false);
        
    }//GEN-LAST:event_btnclearbookActionPerformed

    private void btnclearmovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearmovieActionPerformed
        DefaultTableModel model=(DefaultTableModel)tblmoviesearch.getModel();
        int rows=model.getRowCount();
        if(rows>2)
        {
            for(int i=2;i<rows;i++)
            {
                model.removeRow(2);
            }
        }
        
        tfsearch1.setVisible(false);
        panelprice.setVisible(false);
        combomovietype.setVisible(false);
        
    }//GEN-LAST:event_btnclearmovieActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        new Manager5().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products_Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products_Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products_Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products_Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products_Department().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame IFdeletebook;
    private javax.swing.JInternalFrame IFdeletemovie;
    private javax.swing.JInternalFrame IFnewbook;
    private javax.swing.JInternalFrame IFnewmovie;
    private javax.swing.JButton btnclearbook;
    private javax.swing.JButton btnclearmovie;
    private javax.swing.JButton btndeletebook;
    private javax.swing.JButton btndeletemovie;
    private javax.swing.JButton btnnewbookclear;
    private javax.swing.JButton btnnewbooksave;
    private javax.swing.JButton btnnewmovieclear;
    private javax.swing.JButton btnnewmoviesave;
    private javax.swing.JButton btnsearchbook;
    private javax.swing.JButton btnsearchmovie;
    private javax.swing.JComboBox combobooktype;
    private javax.swing.JComboBox combomovietype;
    private javax.swing.JComboBox combonewbooktype;
    private javax.swing.JComboBox combonewmovietype;
    private javax.swing.JComboBox combosearchcriteria;
    private javax.swing.JComboBox combosearchcriteria1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JMenu menubook;
    private javax.swing.JMenuItem menudeletebook;
    private javax.swing.JMenuItem menudeletemovie;
    private javax.swing.JMenu menuexit;
    private javax.swing.JMenu menumovie;
    private javax.swing.JMenuItem menunewbook;
    private javax.swing.JMenuItem menunewmovie;
    private javax.swing.JScrollPane paneldeletebook;
    private javax.swing.JScrollPane paneldeletemovie;
    private javax.swing.JScrollPane panelnewbook;
    private javax.swing.JScrollPane panelnewmovie;
    private javax.swing.JPanel panelprice;
    private javax.swing.JTable tblbooksearch;
    private javax.swing.JTable tblmoviesearch;
    private javax.swing.JTextField tfdeletebookid;
    private javax.swing.JTextField tfdeletemovieid;
    private javax.swing.JTextField tfmaxprice;
    private javax.swing.JTextField tfminprice;
    private javax.swing.JTextField tfnewbookauthor;
    private javax.swing.JTextField tfnewbookid;
    private javax.swing.JTextField tfnewbookprice;
    private javax.swing.JTextField tfnewbooktitle;
    private javax.swing.JTextField tfnewmovieid;
    private javax.swing.JTextField tfnewmovielead;
    private javax.swing.JTextField tfnewmovietitle;
    private javax.swing.JTextField tfsearch;
    private javax.swing.JTextField tfsearch1;
    // End of variables declaration//GEN-END:variables
}
