
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Micronet
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
         this.setIconImage(new ImageIcon(getClass().getResource("/Images/afridi.jpg")).getImage());
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelcustomertype = new javax.swing.JPanel();
        radiooldcustomer = new javax.swing.JRadioButton();
        radionewcustomer = new javax.swing.JRadioButton();
        btnselectcustomer = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelmanagertype = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combomanager = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        managerpassword = new javax.swing.JPasswordField();
        btnmanageraccount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        panelcustomertype.setBackground(new java.awt.Color(0, 153, 204));
        panelcustomertype.setForeground(new java.awt.Color(0, 153, 255));

        radiooldcustomer.setText("Existing Customer");

        radionewcustomer.setText("New Customer");

        btnselectcustomer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnselectcustomer.setText("Select");
        btnselectcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectcustomerActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Customer");

        javax.swing.GroupLayout panelcustomertypeLayout = new javax.swing.GroupLayout(panelcustomertype);
        panelcustomertype.setLayout(panelcustomertypeLayout);
        panelcustomertypeLayout.setHorizontalGroup(
            panelcustomertypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcustomertypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcustomertypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radiooldcustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radionewcustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(panelcustomertypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnselectcustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
            .addGroup(panelcustomertypeLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelcustomertypeLayout.setVerticalGroup(
            panelcustomertypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcustomertypeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(panelcustomertypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radionewcustomer)
                    .addComponent(btnselectcustomer))
                .addGap(18, 18, 18)
                .addGroup(panelcustomertypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiooldcustomer)
                    .addComponent(btnexit))
                .addGap(17, 17, 17))
        );

        panelmanagertype.setBackground(new java.awt.Color(255, 102, 0));
        panelmanagertype.setForeground(new java.awt.Color(204, 51, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("MANAGER");

        jLabel4.setText("Manager Name");

        combomanager.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combomanager.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIDDHARTH SINGH THAKUR", "PIYUSH SINGH", "KULDEEP KUMAR" }));
        combomanager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combomanagerActionPerformed(evt);
            }
        });

        jLabel6.setText("Password");

        btnmanageraccount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnmanageraccount.setText("Open Manager Account");
        btnmanageraccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageraccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelmanagertypeLayout = new javax.swing.GroupLayout(panelmanagertype);
        panelmanagertype.setLayout(panelmanagertypeLayout);
        panelmanagertypeLayout.setHorizontalGroup(
            panelmanagertypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmanagertypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelmanagertypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelmanagertypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combomanager, 0, 208, Short.MAX_VALUE)
                    .addComponent(managerpassword))
                .addContainerGap())
            .addGroup(panelmanagertypeLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmanagertypeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmanageraccount)
                .addGap(98, 98, 98))
        );
        panelmanagertypeLayout.setVerticalGroup(
            panelmanagertypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmanagertypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addGroup(panelmanagertypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combomanager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelmanagertypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(managerpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnmanageraccount)
                .addGap(25, 25, 25))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("MALIBU NIGHT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelmanagertype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelcustomertype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(panelmanagertype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(panelcustomertype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnselectcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectcustomerActionPerformed
        if(radionewcustomer.isSelected())
        {
           new NewCustomerLetter().setVisible(true);
           this.setVisible(false);
        }
        if(radiooldcustomer.isSelected())
        {
            new OldCustomer().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnselectcustomerActionPerformed

    private void btnmanageraccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageraccountActionPerformed
             String password=managerpassword.getText();
             switch(combomanager.getSelectedIndex())
             {
                 case 0:
                     if(password.equals("siddharth123"))
                     {
                     this.setVisible(false);
                     new Manager1().setVisible(true);
                     }
                     
                     else
                     {
                        JOptionPane.showMessageDialog(this,"Invalid Password");
                        managerpassword.setText("");
                     }
                  break;
                  
                
                     case 1:
                      if(password.equals("piyush123"))
                      {
                     this.setVisible(false);
                     new Manager4().setVisible(true);
                      }
                          else
                     {
                        JOptionPane.showMessageDialog(this,"Invalid Password");
                        managerpassword.setText("");
                     }
                     break;
                     case 2:
                      if(password.equals("kuldeep123"))
                      {
                     this.setVisible(false);
                     new Manager5().setVisible(true);
                      }
                          else
                     {
                        JOptionPane.showMessageDialog(this,"Invalid Password");
                        managerpassword.setText("");
                     }
                     break;
             }
    }//GEN-LAST:event_btnmanageraccountActionPerformed

    private void combomanagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combomanagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combomanagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnmanageraccount;
    private javax.swing.JButton btnselectcustomer;
    private javax.swing.JComboBox combomanager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField managerpassword;
    private javax.swing.JPanel panelcustomertype;
    private javax.swing.JPanel panelmanagertype;
    private javax.swing.JRadioButton radionewcustomer;
    private javax.swing.JRadioButton radiooldcustomer;
    // End of variables declaration//GEN-END:variables

    private Object JFrame(String newCustomerLetter) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
